ni/measurement-plugin-python

README.md
examples/nidaqmx_analog_input/README.md
examples/nidcpower_source_dc_voltage/README.md
examples/nidcpower_source_dc_voltage_with_labview_ui/README.md
examples/nidmm_measurement/README.md
examples/nifgen_standard_function/README.md
examples/niscope_acquire_waveform/README.md
examples/niswitch_control_relays/README.md
examples/nivisa_dmm_measurement/README.md
examples/nivisa_dmm_measurement/measurement.py
examples/nivisa_dmm_measurement/teststand_fixture.py
examples/sample_measurement/README.md

Add a `README.md` file to each example.
Address @rfriedma's feedback about the VISA example:
- Enable simulation by default
- Add a `USE_SIMULATION` variable to `measurement.py`
- When debugging with VS Code, it's easier to edit the file than to create a `launch.json` specifying the command line arguments. 
Fixes #203 
Documents the examples' features, required drivers, and required hardware.
Manually tested `nivisa_dmm_measurement`.
Tested `nivisa_dmm_measurement` in TestStand with `ASRL1::INSTR`.

examples: Add README.md files and address Ryan's feedback on the VISA example

---

examples/nidcpower_source_dc_voltage/_helpers.py
examples/nidcpower_source_dc_voltage/teststand_fixture.py
examples/nidmm_measurement/_helpers.py
examples/nidmm_measurement/teststand_fixture.py
examples/nifgen_standard_function/_helpers.py
examples/nifgen_standard_function/teststand_fixture.py
examples/niscope_acquire_waveform/_helpers.py
examples/niscope_acquire_waveform/teststand_fixture.py
examples/niswitch_control_relays/_helpers.py
examples/niswitch_control_relays/teststand_fixture.py
examples/nivisa_dmm_measurement/_helpers.py
examples/nivisa_dmm_measurement/teststand_fixture.py
ni_measurementlink_service/_internal/discovery_client.py
ni_measurementlink_service/_internal/grpc_servicer.py
ni_measurementlink_service/_internal/service_manager.py
ni_measurementlink_service/measurement/service.py
ni_measurementlink_service/session_management.py
poetry.lock
pyproject.toml
tests/acceptance/test_measurement_service.py
tests/unit/test_metadata.py
tests/unit/test_serialization_strategy.py
tests/unit/test_serializer.py

Update to the latest ni-python-styleguide and fix the errors that we had, primarily D417 errors due to incorrectly formatted doc strings.
Keep up-to-date with the correct style.
None. Documentation and style changes only.

Update to ni-python-styleguide 0.4.0

---

CONTRIBUTING.md
README.md
examples/README.md

Signed-off-by: Brad Keryan <brad.keryan@ni.com>
Clean up readme formatting and fix minor errors (mostly parenthesis usage and capitalization).
Improve readability
None

README.md: Clean up formatting and fix minor errors

---

README.md

Signed-off-by: Brad Keryan <brad.keryan@ni.com>
Change "Measurement UI Editor" to "MeasurementLink UI Editor"
Remove bold from the word "application"
Match application name
None

README.md: Fix reference to MeasurementLink UI Editor

---

ni_measurementlink_generator/pyproject.toml
pyproject.toml

Signed-off-by: Joel Dixon <joel.dixon@ni.com>
Sets the development status to '5 - Production/Stable' prior to our upcoming 1.0 release.
Let developers / community know the next release is ready for consumption and stable.
None. Next pypi upload should include this information.

Setting Development Status to Production/Stable

---

README.md

Add link to MeasurementLink manual.
Make API reference link more prominent. 
Make documentation easier to find.
N/A

README.md: Add link to manual and make API reference link more prominent

---

ni_measurementlink_service/_internal/stubs/ni/measurementlink/measurement/v2/measurement_service_pb2.pyi
ni_measurementlink_service/_internal/stubs/proto/ni/measurementlink/measurement/v2/measurement_service.proto

Updated measurement_service.proto with latest changes from [this PR](https://ni.visualstudio.com/DevCentral/_git/ASW/pullrequest/475543).
Updated measurement_service.proto with latest changes from [this PR](https://ni.visualstudio.com/DevCentral/_git/ASW/pullrequest/475543).
N/A.

Propagated comment changes for measurement_service.proto

---

poetry.lock
pyproject.toml
tests/unit/test_session_management.py

Add unit tests for the `session_management` sub-module.
It has no tests.
Ran new tests.

tests: Add unit tests for session_management

---

ni_measurementlink_generator/pyproject.toml
pyproject.toml

Update the main branch version to 1.2.0-dev0.
We will make 1.1 builds using the releases/1.1 branch.
Unblock development on next release.
None

service, generator: Update main branch version to 1.2.0-dev0

---

README.md
examples/README.md

Add a link to the 1.1.0 example zip file.
Ensure that the README that we upload to PyPI has a link to the 1.1.0 example zip file.
This PR will be cherry-picked into releases/1.1.
None

README.md: Add link to 1.1.0 example zip (which doesn't exist yet)

---

README.md
ni_measurementlink_generator/README.md

Update description of MeasurementLink Support for Python based on content from https://www.ni.com/docs/en-US/bundle/measurementlink/page/measurementlink.html
This will be cherry-picked into releases/1.1.
Consistency with MeasurementLink Manual.
None

README.md: Update intro based on content from MeasurementLink manual

---

README.md
ni_measurementlink_generator/README.md

Update description of MeasurementLink Support for Python based on content from https://www.ni.com/docs/en-US/bundle/measurementlink/page/measurementlink.html
Cherry-picked from https://github.com/ni/measurementlink-python/commit/4112612117f5a619a2b44390e8b429fe717700e3
Consistency with MeasurementLink Manual.
None

[releases/1.1] README.md: Update intro based on content from MeasurementLink manual

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
examples/sample_streaming_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml

Cherry-pick https://github.com/ni/measurementlink-python/pull/325 into releases/1.1
Fix "check examples" workflow.
PR build

[releases/1.1] examples: Disallow click version 8.1.4

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_streaming_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml

Updates release versions of `nidaqmx(0.8.0)/ni-measurementlink-service(1.1.0)` for all examples except `samplemeasurement`.
Refer https://github.com/ni/measurementlink-python/pull/339#discussion_r1268304981
None

[Cherry Pick] 6f79e8f Update release versions in examples

---

README.md
examples/README.md

Update links to examples to reference MeasurementLink 2023 Q4 and link to the 1.2.0 zip file (which doesn't exist yet)
(cherry picked from #381)
Prepare for 1.2.0 release.
N/A

[releases/1.2] README.md: Update links to examples

---

README.md
examples/README.md
ni_measurementlink_generator/README.md
ni_measurementlink_generator/pyproject.toml
pyproject.toml

Update package versions to 1.3.0-dev0.
Update readmes to refer to MeasurementLink 2024 Q1.
Fix dependencies section of generator readme.
Inform customers that the examples in the main branch are targetting 2024 Q1.
None

Update versions for 1.3 and MeasurementLink 2024 Q1

---

examples/game_of_life/start.bat
examples/nivisa_dmm_measurement/start.bat
examples/output_voltage_measurement/start.bat

`game_of_life` and `output_voltage_measurement`:
- Update `start.bat` to use a virtualenv.
`nivisa_dmm_measurement`:
- Remove outdated comments from `start.bat`
Make new examples work when statically registered.
Used `install_examples.py` and ran all affected examples.

examples: Update start.bat to use virtualenv

---

ni_measurementlink_generator/ni_measurementlink_generator/templates/start.bat.mako
ni_measurementlink_generator/tests/test_assets/example_renders/measurement/start.bat
ni_measurementlink_generator/tests/test_assets/example_renders/measurement_with_annotations/start.bat

`ni-measurementlink-generator`:
- Update `start.bat` to use an in-project virtualenv
Match the practices demonstrated by the examples. 
None

generator: Update start.bat to use virtualenv

---

tests/unit/test_discovery_client.py

Update test case names to use given/when/then format.
Follow NI's testing conventions.
PR build

tests: Fix incorrect discovery client test case names

---

.github/workflows/check_examples.yml
.github/workflows/check_nimg.yml
.github/workflows/check_nims.yml
poetry.lock
pyproject.toml

Run `mypy --platform win32` to check typing in Windows-specific code.
Don't let typing errors in Windows-specific code slip through the cracks.
Ran PR workflow.

PR workflow: Run mypy --platform win32

---

examples/.env.sample
examples/.env.simulation
examples/README.md
examples/nidcpower_source_dc_voltage/README.md

- Updated the `NI-DCPower` example's ReadMe file to describe the simulation process.
- Moved `.env.simulation` and `.env.sample` to `examples` directory.
Explains the process of enabling the simulation in the ReadMe file.

examples: Update NI-DCPower readme to describe the .env simulation process

---

.readthedocs.yml

Add a Read the Docs config.
Partial fix for #431 
None. (I can't get RTD to find my dev branch.)

rtd: Add .readthedocs.yml

---

.readthedocs.yml

Cherry-pick #505 into releases/1.0.
Enable displaying 1.0 docs in RTD.
The config has been tested with the main branch.

[releases/1.0] rtd: Add .readthedocs.yml

---

ni_measurementlink_generator/ni_measurementlink_generator/templates/_helpers.py.mako
ni_measurementlink_generator/tests/test_assets/example_renders/measurement/_helpers.py
ni_measurementlink_generator/tests/test_assets/example_renders/measurement_with_annotations/_helpers.py

Update the `_helpers.py.mako` in NIMG.
With all the examples' `_helpers.py` updated, the template file must be updated to be in sync with those changes.
Ran mypy and verified the template changes by building the `ni-measurementlink-generator-1.3.0.whl`.

template: update _helpers.py.mako in NIMG

---

examples/game_of_life/README.md
examples/nidaqmx_analog_input/README.md
examples/nidcpower_source_dc_voltage/README.md
examples/nidigital_spi/README.md
examples/nidmm_measurement/README.md
examples/nifgen_standard_function/README.md
examples/niscope_acquire_waveform/README.md
examples/niswitch_control_relays/README.md
examples/nivisa_dmm_measurement/README.md
examples/output_voltage_measurement/README.md
examples/sample_measurement/README.md

Update VISA example readmes for VISA gRPC support.
Update example readmes to clarify required software versions.
Fix #535 
N/A

examples: Update readmes for VISA gRPC support and to clarify required software versions

---

ni_measurementlink_generator/pyproject.toml
pyproject.toml

Bump main package versions to 1.4.0-dev0.
Preparation for upcoming development in 'main'.
None. Checks should catch any problems.

Bump main packages to 1.4.0-dev0

---

examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml

Fix an example .toml file - forgot the quote at the end of the version.
To make Check_Examples pass in releases/1.3.
Will run check examples on this branch before submitting.

Fix mistake in ni-visa-dmm measurement

---

.github/workflows/Publish_NIMS.yml
README.md
examples/README.md
examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml

Update publish_nims.yml with the changes made in releases/1.3.0. Update examples to use the newly released 1.3.0 packages. Update readmes to account for the new version of MeasurementLink.
Update main for the new 1.3.0 release.
None.

Post publish workflow to update main after the 1.3.0 release

---

examples/game_of_life/measurement.py
examples/nidaqmx_analog_input/teststand_nidaqmx.py
examples/nidcpower_source_dc_voltage/teststand_nidcpower.py
examples/nidigital_spi/teststand_nidigital.py
examples/nidmm_measurement/teststand_nidmm.py
examples/nifgen_standard_function/teststand_nifgen.py
examples/niscope_acquire_waveform/teststand_niscope.py
examples/niswitch_control_relays/teststand_niswitch.py
examples/nivisa_dmm_measurement/_visa_dmm.py
examples/nivisa_dmm_measurement/teststand_nivisa_dmm.py
examples/output_voltage_measurement/_visa_dmm.py
examples/output_voltage_measurement/teststand_nidcpower.py
examples/output_voltage_measurement/teststand_nivisa_dmm.py
examples/sample_measurement/measurement.py

Recent changes to Black flagged our examples as needing updates.
Fix the check examples action.
Ran 'poetry run ni-python-styleguide fix' for each example. These are the results.

Re-run ni-python-styleguide on examples

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
ni_measurementlink_generator/pyproject.toml
pyproject.toml

Loosen poetry-core version constraint to `>=1.0.0`
Internal testing indicates that 1.0 is fine, according to @mshafer-NI
None

pyproject.toml: Loosen poetry-core version constraint

---

.github/workflows/sync_github_issues_to_azdo.yml

The Test Automation Frameworks area path in Azure DevOps has been moved, so reflect that change in where Bugs for GitHub Issues area created.
Without this change, Issues opened against this repo will not have a paired work item created in Azure DevOps for the team
None

Update sync_issues_to_azdo.yml to match AzDO area path update

---

ni_measurementlink_service/_internal/stubs/proto/ni/measurementlink/pin_map_context.proto
ni_measurementlink_service/_internal/stubs/proto/ni/measurementlink/pinmap/v1/pin_map_service.proto
ni_measurementlink_service/_internal/stubs/proto/ni/measurementlink/sessionmanagement/v1/session_management_service.proto
ni_measurementlink_service/_internal/stubs/proto/ni/protobuf/types/xydata.proto

Applies the [style: use an indent of 2 spaces](https://github.com/ni/ni-apis/pull/38) changes from the ni-apis.
To make sure our proto files follow the general [file formatting standards](https://protobuf.dev/programming-guides/style/#standard-file-formatting).
NA.

proto: use an indent of 2 spaces

---

ni_measurementlink_generator/pyproject.toml
pyproject.toml

- Updates the NIMG and NIMS versions in the main branch.
Preparation for the upcoming development in 'main'.
NA.

deps: update NIMS & NIMG versions in main

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/output_voltage_measurement/pyproject.toml

Updates the example's `pyproject.toml` specifying "grpc" as an optional dependency for the nimi drivers.
[AB#2484653](https://dev.azure.com/ni/DevCentral/_workitems/edit/2484653)
NA.

deps: add "grpc" as an optional dependency for the nimi drivers

---

examples/nidcpower_source_dc_voltage_with_multiplexer/README.md
examples/output_voltage_measurement/README.md

A minor documentation update in the examples' README.md.
An attempt to have the `Feature` section uniform across all the examples' README.md
NA. Just documentation updates.

examples: update README.md for uniformity

---

.github/workflows/Publish_NIMS.yml
.github/workflows/check_examples.yml
.github/workflows/check_nimg.yml
.github/workflows/check_nims.yml
.github/workflows/run_unit_tests.yml
CONTRIBUTING.md
README.md
examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml

Poetry recently released 1.8. One feature we've wanted is the 'non-package' pyproject.toml file. This update adds the 'package-mode' to specify if a pyproject.toml is for building a package or not. See https://python-poetry.org/blog/announcing-poetry-1.8.0/
Update the poetry version so we can build non-package projects.
Relying on automated tests.

Move to Poetry version 1.8.2

---

ni_measurementlink_generator/pyproject.toml
pyproject.toml

Bump main package versions to 1.5.0-dev0.
Preparation for upcoming development in 'main'.
None. Checks should catch any problems.

Bump main branch versions to 1.5.0-dev0

---

ni_measurementlink_generator/pyproject.toml
pyproject.toml

Bump package versions prior to releases/1.4 release so the zipped source code will have the right version.
Keep version consistent with the release.
None.

[Releases/1.4] Bump package versions to 1.4.0

---

examples/.env.sample
ni_measurementlink_service/_featuretoggles.py
ni_measurementlink_service/session_management/_client.py
ni_measurementlink_service/session_management/_reservation.py

Removes the multiplexer support feature toggles from the newly added multiplexer-related APIs.
Resolves #620.
Verified the NI-DCPower and NI-DCPower with Multiplexer examples.

nims: remove the multiplexer support feature toggle

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml

Now that we have a prerelease, we don't need to depend on the source code.
Allows the install_examples.py script to succeed without having to modify pyproject.toml.
Ran install_examples.py

Comment out the develop = true

---

CONTRIBUTING.md

The CONTRIBUTING.MD instructions for running `pytest` do not include the necessary steps for all tests to run and for simulating devices as required.
Ensures all tests will be run and not skipped for contributing developers.
Followed instructions and ran all tests to see that they pass and are not skipped.

Update test instructions to include simulation of devices so all tests will run

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/Publish_NIMS.yml
.github/workflows/check_nims.yml
.github/workflows/run_unit_tests.yml
scripts/install_examples.py

Removes additional usages of MeasurementLink. Specifically in the .yml files. I'm not working on any documentaton usages.
Prerequisite to building the first version of the packages without MeasurementLink in the name.
Build

Remove some more usages of MeasurementLink

---

CONTRIBUTING.md
README.md
_docs_source/index.rst
examples/README.md
examples/game_of_life/README.md
examples/nidaqmx_analog_input/README.md
examples/nidcpower_source_dc_voltage/README.md
examples/nidcpower_source_dc_voltage_with_multiplexer/README.md
examples/nidigital_spi/README.md
examples/nidmm_measurement/README.md
examples/nifgen_standard_function/README.md
examples/niscope_acquire_waveform/README.md
examples/niswitch_control_relays/README.md
examples/nivisa_dmm_measurement/README.md
examples/output_voltage_measurement/README.md
examples/sample_measurement/README.md
ni_measurement_plugin_sdk_generator/README.md
ni_measurement_plugin_sdk_service/_internal/stubs/proto/README.md

Applies recent file renames to the markdown files
Keep the markdown files in sync
None

Apply renames to markdown contents

---

examples/game_of_life/_helpers.py
examples/nidaqmx_analog_input/NIDAQmxAnalogInput.seq
examples/nidaqmx_analog_input/_helpers.py
examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.seq
examples/nidcpower_source_dc_voltage/_helpers.py
examples/nidcpower_source_dc_voltage_with_multiplexer/NIDCPowerSourceDCVoltageWithMultiplexer.seq
examples/nidcpower_source_dc_voltage_with_multiplexer/_helpers.py
examples/nidigital_spi/_helpers.py
examples/nidmm_measurement/_helpers.py
examples/nifgen_standard_function/_helpers.py
examples/niscope_acquire_waveform/_helpers.py
examples/niswitch_control_relays/_helpers.py
examples/nivisa_dmm_measurement/_helpers.py
examples/output_voltage_measurement/_helpers.py
examples/sample_measurement/_helpers.py
ni_measurement_plugin_sdk_generator/ni_measurement_plugin_sdk_generator/templates/_helpers.py.mako
ni_measurement_plugin_sdk_generator/tests/test_assets/example_renders/measurement/_helpers.py
ni_measurement_plugin_sdk_generator/tests/test_assets/example_renders/measurement_with_annotations/_helpers.py

Updates .seq files (and corresponding .py files) according to [AB!737109](https://dev.azure.com/ni/DevCentral/_git/ASW/pullrequest/737109)
(Note that the .py files were updated manually; I didn't reapply the .mako template, since some were out-of-date already and I don't know if that was intentional. Let me know if I should reapply the template.)
Renames
None

Update TestStand sequences with renames

---

ni_measurement_plugin_sdk_service/discovery/_support.py

Updates the discovery client to look for the discovery service JSON at `NISHAREDDIR64/Services/Services.json`.
The path for the discovery service JSON is being changed, the client needs to look for it in the new location.
Ran `pytest` locally.

Update discovery client JSON service path

---

examples/nidigital_spi/NIDigitalSPI.seq
examples/nidmm_measurement/NIDmmMeasurement.seq
examples/nifgen_standard_function/NIFgenStandardFunction.seq
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.seq
examples/niswitch_control_relays/NISwitchControlRelays.seq
examples/nivisa_dmm_measurement/NIVisaDmmMeasurement.seq

Updates .seq files according to [AB!737109](https://dev.azure.com/ni/DevCentral/_git/ASW/pullrequest/737109), that were missed in #758 
Renames
None

Update missed TestStand sequences with renames

---

scripts/install_examples.py
tests/unit/test_discovery_client.py

Updates the SERVICES_PATH and the Discovery Service .exe name
Renames
None

Update path names in .py code

---

examples/game_of_life/.serviceignore
examples/nidaqmx_analog_input/.serviceignore
examples/nidcpower_source_dc_voltage/.serviceignore
examples/nidcpower_source_dc_voltage_with_multiplexer/.serviceignore
examples/nidigital_spi/.serviceignore
examples/nidmm_measurement/.serviceignore
examples/nifgen_standard_function/.serviceignore
examples/niscope_acquire_waveform/.serviceignore
examples/niswitch_control_relays/.serviceignore
examples/nivisa_dmm_measurement/.serviceignore
examples/output_voltage_measurement/.serviceignore
examples/sample_measurement/.serviceignore

Cherry-pick "Add .serviceignore files to the examples" commit from main.
Needed for releases / 2.0
None - straight cherry-pick

[releases/2.0]: Cherry-pick 'Add .serviceignore files to the examples'

---

.github/workflows/Publish_NIMS.yml

Fix the working directory for the poetry commands related to the service. Doing this directly in releases/2.0. If I succeed, I'll make the same changes in main.
Publish_NIMS.yml failed.
None. Will re-run the publish.

[releases/2.0] Fix working directory for Publish_NIMS.cs

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
packages/generator/pyproject.toml
packages/sdk/pyproject.toml
packages/service/pyproject.toml

Updates versions in pyproject.toml and for the examples. Updates the sdk package to depend on >=2.0 of ni-measurement-plugin-sdk-generator and ni-measurement-plugin-sdk-service.
Standard [release process](https://github.com/ni/measurement-plugin-python/wiki/Release-Process)
None

[releases/2.0] Pre-publish steps, updating versions to final 2.0.0 version

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml

Update versions for examples to 2.0.0 in main.
Standard release process
Installed some examples to ensure the version is available.

Bump examples to latest released versions in main

---

.github/workflows/Publish_NIMS.yml
.github/workflows/check_nimg.yml
.github/workflows/check_nims.yml

Replace `poetry lock --check` with `poetry check --lock`.
```poetry lock --check is deprecated, use `poetry check --lock` instead.```
PR build.

GitHub: Update poetry lock checking

---

CONTRIBUTING.md
README.md
examples/README.md
packages/service/README.md

- Fix broken links to documentation.
- Update example path in examples/README.md that still referenced measurementlink-python and dc_measurement.
- Update gRPC stub info in CONTRIBUTING.md to use correct paths, link to ni-apis repo, and reference Git submodules.
Improve documentation.
N/A

README.md: Fix documentation links and minor issues

---

.github/workflows/sync_github_issues_to_azdo.yml

Update the area path for AzDO bugs to the udpdated team.
New ownership of the repos.
None. Simple change will test after submission.

Update area path to HW Config Amber

---

packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

- Improve the accessing of values from the metadata dictionary during the Measurement Plug-In Client generation.
- This implementation contains the dictionary accessing through `get` method, by which the errors on accessing the dictionary while client generation for LabVIEW are averted.
- Existing automation test passed.
- Done manual testing

[Minor] Improve the dictionary value accessing

---

examples/game_of_life/.serviceignore
examples/nidaqmx_analog_input/.serviceignore
examples/nidcpower_source_dc_voltage/.serviceignore
examples/nidcpower_source_dc_voltage_with_multiplexer/.serviceignore
examples/nidigital_spi/.serviceignore
examples/nidmm_measurement/.serviceignore
examples/nifgen_standard_function/.serviceignore
examples/niscope_acquire_waveform/.serviceignore
examples/niswitch_control_relays/.serviceignore
examples/nivisa_dmm_measurement/.serviceignore
examples/output_voltage_measurement/.serviceignore
examples/sample_measurement/.serviceignore

Fixes #886 
Per Ryan F. the correct casing is
> it's capital "I" everywhere that the P is also capitalized
Correct the capitalization in the repo
None - docs and comments only

Update Plug-in to Plug-In

---

CONTRIBUTING.md

Update `CONTRIBUTING.md` for recent changes:
- The packages are now in the `/packages` directory.
- This repo now uses Git submodules.
- The section on `ni-python-styleguide` was incomplete and there was no documentation on running Mypy or Bandit.
I also renamed/moved some sections, changed to use `poetry run`, and converted section headings to title case.
Provide better guidance to contributors.
N/A

CONTRIBUTING.md: Update for repo layout, submodules, and new lint tools

---

packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py

Cherry-pick the change in PR https://github.com/ni/measurement-plugin-python/pull/915.

[releases/2.1] Cherry-pick: [High Priority] Update default value for the pin map sites

---

ThirdPartyNotices.txt
packages/generator/ni_measurement_plugin_sdk_generator/__init__.py
packages/generator/pyproject.toml
packages/sdk/ni_measurement_plugin_sdk/__init__.py
packages/sdk/pyproject.toml
packages/service/ni_measurement_plugin_sdk_service/__init__.py
packages/service/pyproject.toml

Following #898, to maintain consistency this pull request updates the other instances of the "Plug-In" with the correct casing.
Maintain a consistent casing for the term "Plug-In".
NA.

docs: Update plugin to Plug-In to maintain consistency

---

ThirdPartyNotices.txt
packages/generator/ni_measurement_plugin_sdk_generator/__init__.py
packages/generator/pyproject.toml
packages/sdk/ni_measurement_plugin_sdk/__init__.py
packages/sdk/pyproject.toml
packages/service/ni_measurement_plugin_sdk_service/__init__.py
packages/service/pyproject.toml

Cherry-pick #957 into releases/2.1

[releases/2.1] Cherry-pick: docs: Update plugin to Plug-In to maintain consistency (#957)

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
packages/generator/pyproject.toml
packages/service/pyproject.toml

Pre-publish steps for releases/2.1.
Standard release procedure.
N/A - PR

[releases/2.1] pre-publish steps

---

.github/workflows/CI.yml
.github/workflows/Publish_NIMS.yml

Cherry pick #970, #971 from releases/2.1 to main.
Allows us to do a prerelease or release from main where the generator (and possibly the examples) depend on the service version we're about to publish.
None

[main] Cherry-pick from 2.1 regarding checks for nimg

---

README.md
examples/README.md
examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml

Update examples to use the newly released 2.3.0 packages. Update readmes to account for the new version of Measurement-plugin.
Standard Release Process. Update main after the new 2.3.0 release.
None

Post publish workflow to update main after 2.3.0 release

---

.github/workflows/Publish_NIMS.yml
.github/workflows/check_examples.yml
.github/workflows/check_nimg.yml
.github/workflows/check_nims.yml
.github/workflows/run_unit_tests.yml

Use https://github.com/ni/python-actions/ to set up Python and Poetry.
Single-source default Python and Poetry versions.
Enable Poetry caching.
In the future, this will enable pinning Poetry dependencies or deploying workarounds.
PR build

github: Use ni/python-actions

---

README.md
examples/README.md
examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml

Update examples to use the newly released 2.3.1 packages. Update readmes to account for the new version of Measurement-plugin.
Standard Release Process. Update main after the new 2.3.1 release.
None

Post publish workflow to update main after 2.3.1 release

---

.github/workflows/sync_github_issues_to_azdo.yml

Updates AzDO area path to which issues from the repo are synchronized with.
Matches area path for current team monitoring issues.
N/A

Update area path for syncing issues with AzDO

---

packages/service/poetry.lock
packages/service/pyproject.toml

Apply the new package references from #1244 that were put directly into releases/3.0
Correct dependency references.
PR

Add direct references to packages used in service

---

packages/generator/pyproject.toml
packages/sdk/pyproject.toml
packages/service/pyproject.toml

Updates versions to 3.0.1 prior to patch release.
We need a new version to fix some imports we took out without redirects.
PR

Bump versions to 3.0.1 for patch release
