ni/measurement-plugin-python

examples/nifgen_standard_function/NIFgenStandardFunction.measui
examples/nifgen_standard_function/NIFgenStandardFunction.seq
examples/nifgen_standard_function/measurement.py

Signed-off-by: Chris Delpire <chris.delpire@ni.com>
Removes the abort_when_done parameter from our FGEN example measurement. We tested with hardware and determined that this parameter did not have any effect. 
I also updated the measui to remove the control for this parameter, and I tried updating the seq file. **Can someone else pull this down and validate it on their machine?** The diff is gnarly.
We shouldn't ship an example with a non-functional parameter.
Successfully ran TestStand sequence using simulated PXIe-5423 (2CH).
[AB#2273840](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2273840)

Removing abort_when_done from FGEN example.

---

examples/nidcpower_source_dc_voltage/measurement.py
examples/nifgen_standard_function/measurement.py

Signed-off-by: Chris Delpire <chris.delpire@ni.com>
1. `nidcpower.DriverError` does not exist. ~It should be `nidcpower.Error`.~ It should be `nidcpower.errors.DriverError`. (Fixed fgen too)
2. When testing with real hardware and adding a source delay, the error code I got was `-1074097933` (`kErrorTimeoutExceeded`).
Fixed the error handling and added the additional error code check.
Current example does not support source delay with hardware.
Tested on a machine with an actual SMU device.

Replacing DriverError with Error. Adding additional error code for timeout exceeded error.

---

examples/nidaqmx_analog_input/measurement.py
examples/nidcpower_source_dc_voltage/measurement.py
examples/nidmm_measurement/measurement.py
examples/nifgen_standard_function/measurement.py
examples/niscope_acquire_waveform/measurement.py
examples/niswitch_control_relays/measurement.py
examples/nivisa_dmm_measurement/measurement.py
examples/sample_measurement/measurement.py
ni_measurementlink_generator/ni_measurementlink_generator/templates/measurement.py.mako
ni_measurementlink_generator/tests/test_assets/example_renders/example.py
ni_measurementlink_service/measurement/service.py
tests/assets/example.serviceconfig
tests/integration/test_service_manager.py
tests/unit/test_service.py

Signed-off-by: Chris Delpire <chris.delpire@ni.com>
Rather than duplicating the service info, measurements should just parse their .serviceconfig file so that information can be single sourced.
Current this PR updates the `MeasurementService` `__init__` method to take in the .serviceconfig file path, version, and UI path. I have only updated 1 example so that we can discuss if this is the correct approach or not.
#202 
Once we agree on an implementation, this should be merge to prevent duplication of information between the .serviceconfig and measurement.py files.
Ran the measurement and successfully connected to it via MeasurementLink UI Editor.

Updating MeasurementService __init__ to parse .serviceconfig.

---

examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.pinmap
examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltageMultiSite.pinmap
examples/nidcpower_source_dc_voltage/README.md

Updates pinmaps in `nidcpower_source_dc_voltage` example to have one pin/channel.
Fixes [Bug 2275162](https://ni.visualstudio.com/DevCentral/_workitems/edit/2275162): DCPower Example does not work with single channel SMUs (GitHub Issue #215)
Manually tested.

Update pinmaps in nidcpower_source_dc_voltage example to have one pin/channel

---

README.md
examples/README.md

Signed-off-by: Brad Keryan <brad.keryan@ni.com>
- Move the example content from /README.md to /examples/README.md.
- Add a note about `install_examples.py`.
- Update "note" boxes in top-level README.
- Hyperlink the PyPI README to the examples directory on GitHub.
- Shorten the README that we upload to PyPI.
- Fix broken "PoetryInstallFail" image link when viewing the readme on PyPI.
None

README.md: Move example content into examples/README.md

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml

Make the examples depend on a specific version of ni-measurement-service, 1.0.0 as of now instead of "*" which would always take the latest.
fixes #209 
We know the examples won't break as we add new potentially breaking code to the repo.
None.

Make examples specifically depend on 1.0.0 to avoid future breakages

---

_docs_source/conf.py
_docs_source/index.rst

Adds `autoapi/index` to our index.rst. This will cause pages from autoapi to appear in the sidebar. Additionally, I set the `navigation_depth` of the `html_theme_options` to -1 in the conf.py to allow everything to appear in the sidebar.
See issue #231
Built the documentation locally. Once you click API Reference you will see the page tree in the sidebar.

Adding autoapi/index to index.rst so api shows up in sidebar.

---

examples/README.md
scripts/install_examples.py

Update instructions and script which installs examples. This is a follow-up to https://github.com/ni/measurementlink-python/commit/007f087a018e3614f0370a05f9abc58d240d320a which was mistakenly submitted directly to main.
The .venv should not be copied when copying an example or measurement to statically register it. The venv must be re-created in place to be fully valid.
Fixes #235 
Tested the script locally and ensured that the .venv created has no references to the original directory from the repo.

Update static registration readme and script

---

.github/workflows/Publish_NIMS.yml
poetry.lock
pyproject.toml

Add a `docs` dependency group for Sphinx and related packages.
Install the `docs` dependency group when building documentation.
Update the `dev` dependency group to use Poetry 1.2+ syntax.
Work around flake8/Sphinx dependency version conflict that causes errors like this one:
```
PS C:\dev\measurementlink-python> poetry run ni-python-styleguide lint
Traceback (most recent call last):
File "C:\Dev\measurementlink-python\.venv\lib\site-packages\flake8\plugins\finder.py", line 296, in _load_plugin
obj = plugin.entry_point.load()
File "C:\Users\bkeryan\.pyenv\pyenv-win\versions\3.9.13\lib\importlib\metadata.py", line 86, in load
module = import_module(match.group('module'))
File "C:\Users\bkeryan\.pyenv\pyenv-win\versions\3.9.13\lib\importlib\__init__.py", line 127, in import_module
return …
```

Work around flake8/Sphinx dependency version conflict

---

ni_measurementlink_generator/ni_measurementlink_generator/template.py
ni_measurementlink_generator/pyproject.toml

ni_measurementlink_generator:
- Mako usage:
- Let Mako read the template file. 
- Specify the input/output encodings. 
- This causes Mako to render the template as `bytes` rather than `str`. Using `bytes` avoids incorrect newline conversion that would result in `\r\r\n` line endings on Windows.
- This preserves the bug fix from https://github.com/ni/measurementlink-python/pull/240
- Error handling:
- Report Mako template errors as errors rather than printing to stdout and returning success. Use the `logging` module to trace the Mako stack trace (with the correct Mako line numbers), then use `click.ClickException` to return a user-visible error.
- Report invalid parameters using `click.BadParameter`, avoiding a stack trace.
- Reformat option descriptions to use single quotes for strings to …

generator: Improve Mako usage, error handling, and type annotations

---

examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.seq
examples/nidcpower_source_dc_voltage/_helpers.py
examples/nidcpower_source_dc_voltage/teststand_fixture.py

- Updates the TestStand sequence in the DC-Power example measurement to make it simpler by moving the process setup and process cleanup steps to the main sequence.
- Combines the logic for registering pin map into a single step in the Setup section. Previously this was handled in three steps.
Based on the feedback discussed in this [Teams post](https://teams.microsoft.com/l/message/19:36f0e963feb84c0c8122e6ddfbe7df7b@thread.tacv2/1676494204834?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=a092c504-be1c-4d21-9ef4-068a40ca6974&parentMessageId=1676494204834&teamName=MeasurementLink%20%26%20ETW%20Global%20Collaboration&channelName=Roadmap%20Input%20and%20Feature%20Ideas&createdTime=1676494204834&allowXTenantAccess=false), moving the process setup and process cleanup steps to the main …

Updated the TestStand sequence of NI DCPower measurement to make it simpler

---

examples/nidcpower_source_dc_voltage/README.md
examples/nidmm_measurement/NIDmmMeasurement.seq
examples/nidmm_measurement/README.md
examples/nidmm_measurement/_helpers.py
examples/nidmm_measurement/teststand_fixture.py
examples/nifgen_standard_function/NIFgenStandardFunction.seq
examples/nifgen_standard_function/README.md
examples/nifgen_standard_function/_helpers.py
examples/nifgen_standard_function/teststand_fixture.py
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.seq
examples/niscope_acquire_waveform/README.md
examples/niscope_acquire_waveform/_helpers.py
examples/niscope_acquire_waveform/teststand_fixture.py
examples/niswitch_control_relays/NISwitchControlRelays.seq
examples/niswitch_control_relays/README.md
examples/niswitch_control_relays/_helpers.py
examples/niswitch_control_relays/teststand_fixture.py
examples/nivisa_dmm_measurement/NIVisaDmmMeasurement.seq
examples/nivisa_dmm_measurement/README.md
examples/nivisa_dmm_measurement/_helpers.py
examples/nivisa_dmm_measurement/teststand_fixture.py

- Updates the TestStand sequence in the example measurement to make it simpler by moving the process setup and process cleanup steps to the main sequence.
-  The sequence update and their relevant python functions are done for below examples:
- DMM
- FGEN
- SCOPE
- SWITCH
- VISA DMM
- Combines the logic for registering pin map into a single step in the Setup section. Previously this was handled in three steps.
- Updated the `Readme.md` file for the updated examples.
Based on the feedback discussed in this [Teams post](https://teams.microsoft.com/l/message/19:36f0e963feb84c0c8122e6ddfbe7df7b@thread.tacv2/1676494204834?tenantId=87ba1f9a-44cd-43a6-b008-6fdb45a5204e&groupId=a092c504-be1c-4d21-9ef4-068a40ca6974&parentMessageId=1676494204834&teamName=MeasurementLink%20%26%20ETW%20Global%20Collab …

Updated the TestStand sequence of measurement examples to make it simpler (DMM, FGEN, SCOPE, SWITCH, VISA DMM)

---

ni_measurementlink_generator/conftest.py
ni_measurementlink_generator/poetry.lock
ni_measurementlink_generator/pyproject.toml
ni_measurementlink_generator/tests/acceptance/test_generator.py
ni_measurementlink_generator/tests/conftest.py
ni_measurementlink_generator/tests/test_measurement_generator.py
ni_measurementlink_service/__init__.py
ni_measurementlink_service/_internal/grpc_servicer.py
poetry.lock
pyproject.toml
tests/acceptance/test_measurement_service.py
tests/integration/test_service_manager.py
tests/unit/test_discovery_client.py
tests/unit/test_metadata.py
tests/unit/test_serialization_strategy.py
tests/unit/test_serializer.py
tests/unit/test_service.py
tests/utilities/fake_discovery_service.py

Update `ni-python-styleguide` to version 0.4.1.
Fix syntax of `noqa` comments. To ignore a specific error, you must put a colon after `noqa`, or else it ignores all errors. 
Fix import order in `__init__.py`.
Remove docstrings from test case functions.
Fixes #250 
Removes boilerplate docstrings from tests.
Ran `ni-python-styleguide lint` and `pytest`.

Upgrade ni-python-styleguide to version 0.4.1

---

ni_measurementlink_service/_internal/grpc_servicer.py
pyproject.toml

Currently, measurement services send outputs to the client when the measurement is complete, by returning a list/tuple of output values. This PR allows measurement services to send outputs to the client during the measurement, by yielding a list/tuple of output values.
When accessed via the `ni.measurementlink.measurement.v1.MeasurementService` interface, only the last update is sent to the client.
The final update may use either a `yield` or `return` statement, so that adding a `yield` statement to a previously working measurement service doesn't cause the return value to be ignored. This is why this code catches `StopIteration`: to inspect the return value stored in the exception's `value` field.
Also:
- Update the `ni-measurementlink-service` version to 1.1.0a0
AB#2371309
- Ran …

service: Add support for updating outputs during the measurement

---

ni_measurementlink_generator/pyproject.toml
pyproject.toml

- Specify --doctest-modules. If we add doctests to the main package, we should run them.
- Specify --strict-markers. Require markers to be declared to avoid typos and ensure they are documented.
- Enable ImportWarning and ResourceWarning. By default, Python filters out DeprecationWarning, DeprecationPendingWarning, ImportWarning, and ResourceWarning. Pytest enables DeprecationWarning and DeprecationPendingWarning but not the others. Enabling ResourceWarning in nidaqmx-python has caught some resource leaks.
- generator: Specify testpaths to test pytest where to search for tests.
- generator: Specify --ignore to prevent pytest from looking for doctests in test_assets.
> **Note**
> I chose not to enable --cov or --verbose in pyproject.toml. These are still specified in the PR workflow. …

tests: Update pytest options for doctests, markers, testpaths, and warnings

---

.github/workflows/PR.yml
.github/workflows/Publish_NIMS.yml

Create `measurementlink-python-examples-1.1.0a0.zip` and `measurementlink-python-examples-1.1.0a0.tar.gz` and upload them as release assets.
The archive includes the contents of the examples directory and does not have a top-level directory:
```
PS D:\dev\measurementlink-python> git archive -o dist\measurementlink-python-examples-1.1.0a0.tar.gz main:examples/
PS D:\dev\measurementlink-python> tar tzvf .\dist\measurementlink-python-examples-1.1.0a0.tar.gz
-rw-rw-r--  0 root   root     4485 May 08 15:06 README.md
drwxrwxr-x  0 root   root        0 May 08 15:06 nidaqmx_analog_input/
-rw-rw-r--  0 root   root     1536 May 08 15:06 nidaqmx_analog_input/NIDAQmxAnalogInput.instudioproj
...
drwxrwxr-x  0 root   root        0 May 08 15:06 nidcpower_source_dc_voltage/
-rw-rw-r--  0 root   root …
```

Publish workflow: Upload archive of examples as release assets

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml
poetry.lock
pyproject.toml

`grpc-stubs` is a "stub-only" package that provides type information for most of `grpcio`.
Enable type checking gRPC calls.
Ran mypy on ni_measurement_service and one example. The PR build will validate the other examples.

service, examples: Use grpc-stubs for type information

---

ni_measurementlink_service/_internal/stubs/ni/measurementlink/measurement/v1/measurement_service_pb2.pyi
ni_measurementlink_service/_internal/stubs/ni/measurementlink/measurement/v2/measurement_service_pb2.pyi
ni_measurementlink_service/_internal/stubs/ni/measurementlink/sessionmanagement/v1/session_management_service_pb2.pyi
pyproject.toml
scripts/generate_grpc_stubs.py

mypy-protobuf generates `.pyi` type stubs for our protobuf codegen (`*_pb2.py`, not `*_pb2_grpc.py`). However, we aren't fixing up the imports for these files, so we currently exclude them from mypy type checking.
Update `generate_grpc_stubs.py` to fix up the imports in `*_pb2.pyi`.
Update `pyproject.toml` to stop excluding `*_pb2.py` and only exclude `*_pb2_grpc.py`, with a comment explaining why.
Make mypy type checking more accurate and exclude fewer files from type checking.
Ran `poetry run mypy ni_measurementlink_service`

scripts: Fix imports in .pyi type stubs

---

ni_measurementlink_service/_internal/grpc_servicer.py
ni_measurementlink_service/measurement/service.py
ni_measurementlink_service/session_management.py

Add type annotations to the public `MeasurementContext` class as well as the internal implementation class.
Change `MeasurementContext.add_cancel_callback()` to expect a callable with 0 arguments that returns None, not just any callable.
Change `MeasurementContext.pin_map_context` to return a `ni_measurementlink_service.session_management.PinMapContext` rather than the corresponding protobuf message.
It makes Intellisense and type checking more accurate.
It fixes a type mismatch between the session management API and the measurement context API.
`poetry run pytest -v`
`poetry run mypy -p ni_measurement_service`
Tested the NI-DCPower and NI-Digital examples in InstrumentStudio, TestStand, and with mypy.

service: Add missing type info to MeasurementContext & use correct types

---

examples/nidigital_spi/measurement.py

Fixes Issue #259 
The [apply_levels_and_timing API ](https://nimi-python.readthedocs.io/en/master/nidigital/class.html#apply-levels-and-timing) allows the use of the file name (without extension) or the use of an absolute path. Since the file names are passed in as relative paths, while it is necessary to resolve to an absolute path if calling `load_specifications_levels_and_timing`, the name can be used when calling `apply_levels_and_timing`. This allows for when the files have been loaded from a different location at session initialization time, as is the case with the TestStand sequence.
Make the nidigital_spi example work in cases where the TestStand sequence initializes the session with files that are found in a different location than next to the measurement service.
Followed the …

Use timing and levels sheets name when applying rather than path

---

examples/nidaqmx_analog_input/_helpers.py
examples/nidaqmx_analog_input/_nidaqmx_helpers.py
examples/nidaqmx_analog_input/measurement.py
examples/nidaqmx_analog_input/teststand_fixture.py
examples/nidcpower_source_dc_voltage/_helpers.py
examples/nidcpower_source_dc_voltage/_nidcpower_helpers.py
examples/nidcpower_source_dc_voltage/measurement.py
examples/nidcpower_source_dc_voltage/teststand_fixture.py
examples/nidigital_spi/_helpers.py
examples/nidigital_spi/_nidigital_helpers.py
examples/nidigital_spi/measurement.py
examples/nidigital_spi/teststand_fixture.py
examples/nidmm_measurement/_helpers.py
examples/nidmm_measurement/_nidmm_helpers.py
examples/nidmm_measurement/measurement.py
examples/nidmm_measurement/teststand_fixture.py
examples/nifgen_standard_function/_helpers.py
examples/nifgen_standard_function/_nifgen_helpers.py
examples/nifgen_standard_function/measurement.py
examples/nifgen_standard_function/teststand_fixture.py
examples/niscope_acquire_waveform/_helpers.py
examples/niscope_acquire_waveform/_niscope_helpers.py
examples/niscope_acquire_waveform/measurement.py
examples/niscope_acquire_waveform/teststand_fixture.py
examples/niswitch_control_relays/_helpers.py
examples/niswitch_control_relays/_niswitch_helpers.py
examples/niswitch_control_relays/measurement.py
examples/niswitch_control_relays/teststand_fixture.py
examples/nivisa_dmm_measurement/_helpers.py
examples/nivisa_dmm_measurement/measurement.py

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).
This Pull request updates the measurement link examples to match the changes recently done in the NI DC power examples.
The updates are as follows,
1. Created new driver specific helper files which contains the session creation logic.
2. Update the general helper files to match the updates done in ni dcpower example.
3. Update the reservation and session creation logic to match the updates done in ni dcpower example.
Updates the measurement link example files to match the latest changes done to measurement service and the helpers.
Manually ran all the tests and verified the functionality of them.

Update measurement link examples to match dcpower example changes.

---

examples/README.md
examples/nidmm_measurement/NIDmmMeasurement.seq
examples/nidmm_measurement/measurement.py
examples/nifgen_standard_function/NIFgenStandardFunction.seq
examples/nifgen_standard_function/measurement.py
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.seq
examples/nivisa_dmm_measurement/NIVisaDmmMeasurement.seq
examples/nivisa_dmm_measurement/measurement.py

- Updates the TestStand sequence files for the examples that use enums via opening them up and clicking "Reload Measurement Parameters".
- Fixed an issue where some of these examples used enums that did not have a zero-value.
[AB#2426140](https://ni.visualstudio.com/DevCentral/_backlogs/backlog/InstrumentStudio%20Platform/Features/?workitem=2426140)
- Manually validated that the examples services starts successfully.
- Manually validated that we can connect to the services in TestStand and reload measurement parameters.
- Manually inspected that the reloaded measurement parameters specify enum for enum parameters.

Update Example Services' TestStand Sequences for Enum Support

---

examples/nidaqmx_analog_input/measurement.py
examples/nidcpower_source_dc_voltage/_nidcpower_helpers.py
examples/nidcpower_source_dc_voltage/measurement.py
examples/nidigital_spi/_nidigital_helpers.py
examples/nidigital_spi/measurement.py
examples/nidmm_measurement/_nidmm_helpers.py
examples/nidmm_measurement/measurement.py
examples/nifgen_standard_function/_nifgen_helpers.py
examples/nifgen_standard_function/measurement.py
examples/niscope_acquire_waveform/_niscope_helpers.py
examples/niscope_acquire_waveform/measurement.py
examples/niswitch_control_relays/_niswitch_helpers.py
examples/niswitch_control_relays/measurement.py
examples/nivisa_dmm_measurement/README.md
examples/nivisa_dmm_measurement/_visa_helpers.py
examples/nivisa_dmm_measurement/measurement.py
examples/nivisa_dmm_measurement/teststand_fixture.py

The reserve call has a large comment about the reservation timeout. Extracting a constant allows us to move the comment outside of the call.
Also:
- Turn `USE_SIMULATION` and `SIMULATION_YAML_PATH` comments into docstrings.
- Single-source VISA `USE_SIMULATION` constant.
Make examples more readable.
Manually tested NI-DCPower example.

examples: Simplify reserve call by extracting reservation timeout constant

---

scripts/install_examples.py

Make `install_examples.py` update `ni-measurementlink-service = { path = "../.."` to use an absolute path.
> **Note**
>
> If your Git repo has a different drive letter than `%ProgramData%`, this still doesn't work. This is a Poetry limitation: it wants to write relative paths into `poetry.lock`, and relative paths can't span drive letters.
Make it easier to install examples with local builds.
Manually tested.

scripts: Make install_examples.py work with path="../.."

---

README.md

Update the main README to match the examples/README and tell the user not to copy their venv but recreate it in place.
Fixes #298 
Consistent instructions for customers.
None. Documentation only change.

Update static registration instructions not to tell the user to copy venv

---

README.md
examples/README.md

Add a link to the 1.1.0 example zip file.
Cherry-picked from https://github.com/ni/measurementlink-python/pull/304
Ensure that the README that we upload to PyPI has a link to the 1.1.0 example zip file.
None

README.md: Add link to 1.1.0 example zip (which doesn't exist yet)

---

examples/nidaqmx_analog_input/NIDAQmxAnalogInput.serviceconfig
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.serviceconfig
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/NIDigitalSPI.serviceconfig
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/NIDmmMeasurement.serviceconfig
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/NIFgenStandardFunction.serviceconfig
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.serviceconfig
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/NISwitchControlRelays.serviceconfig
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/NIVisaDmmMeasurement.serviceconfig
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_measurement/SampleMeasurement.serviceconfig
examples/sample_measurement/pyproject.toml
examples/sample_streaming_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml
ni_measurementlink_generator/ni_measurementlink_generator/templates/measurement.serviceconfig.mako
ni_measurementlink_generator/tests/test_assets/example_renders/SampleMeasurement.serviceconfig

Update examples to download `ni-measurementlink-service` from PyPI.
Update MI examples to specify `extras = ["grpc"]` for nimi-python dependencies.
Update example `.serviceconfig` files to advertise the measurement v2 interface.
Remove a comment about Poetry 1.2 being required for `path = "../.."`. The example pyproject.toml files now use other Poetry 1.2+ features, so this is no longer relevant.
This will be cherry-picked into releases/1.1.
Prepare for release
Fixes #239 
Ran `install_examples.py` and manually tested all MI examples.

examples: Update dependencies and providedInterfaces

---

examples/nidaqmx_analog_input/NIDAQmxAnalogInput.serviceconfig
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.serviceconfig
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/NIDigitalSPI.serviceconfig
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/NIDmmMeasurement.serviceconfig
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/NIFgenStandardFunction.serviceconfig
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.serviceconfig
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/NISwitchControlRelays.serviceconfig
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/NIVisaDmmMeasurement.serviceconfig
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_measurement/SampleMeasurement.serviceconfig
examples/sample_measurement/pyproject.toml
examples/sample_streaming_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml
ni_measurementlink_generator/ni_measurementlink_generator/templates/measurement.serviceconfig.mako
ni_measurementlink_generator/tests/test_assets/example_renders/SampleMeasurement.serviceconfig

Cherry picked from https://github.com/ni/measurementlink-python/pull/306:
---
Update examples to download `ni-measurementlink-service` from PyPI.
Update MI examples to specify `extras = ["grpc"]` for nimi-python dependencies.
Update example `.serviceconfig` files to advertise the measurement v2 interface.
Remove a comment about Poetry 1.2 being required for `path = "../.."`. The example pyproject.toml files now use other Poetry 1.2+ features, so this is no longer relevant.
Prepare for release
Fixes #239 
Ran `install_examples.py` and manually tested all MI examples.

examples: Update dependencies and providedInterfaces (#306)

---

ni_measurementlink_generator/ni_measurementlink_generator/templates/measurement.serviceconfig.mako

Generate JSON using the `json` module instead of manually generating it in the template.
Always produces well-formed JSON, even when string escaping is required.
Simplifies maintenance: no need to quote strings, avoid trailing commas, etc.
Ran unit tests.

generator: Generate JSON using the `json` module

---

ni_measurementlink_service/_internal/discovery_client.py

- Update `discovery_client`  to ensure discovery service is started before measurement service is trying to register to it.
- If discovery service key file doesn't exist, get the discovery service exe file path and execute the process.
Cherry picked from https://github.com/ni/measurementlink-python/commit/5af9b2f5923ae5eb24c80a14aaecfe510059b280
- This implements [User Story 2358867](https://dev.azure.com/ni/DevCentral/_workitems/edit/2358867): Launch Discovery service just-in-time in Python
- Manually tested sample_measurement with and without discovery service running.

[releases/1.1] ni_measurementlink_service: Launch discovery service just-in-time before registering a measurement service

---

examples/nidaqmx_analog_input/pyproject.toml

Use the `nidaqmx-python` 0.8.0-dev0 prerelease that is on PyPI.
This will be cherry-picked into releases/1.1.
Disable downloading `nidaqmx-python` from GitHub.
Manually tested example.

examples: Use nidaqmx-python prerelease on PyPI

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
examples/sample_streaming_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml

Update the examples and ni-measurementlink-generator to disallow click version 8.1.4, because it causes mypy errors:
```
_helpers.py:209: error: Argument 1 has incompatible type "F"; expected <nothing>  [arg-type]
_helpers.py:214: error: Need type annotation for "use_grpc_device_option"  [var-annotated]
_helpers.py:220: error: Need type annotation for "grpc_device_address_option"  [var-annotated]
```
Fix "check examples" workflow.
PR build

examples: Disallow click version 8.1.4

---

examples/nidaqmx_analog_input/pyproject.toml

Use the `nidaqmx-python` 0.8.0-dev0 prerelease that is on PyPI.
Cherry-picked from commit 0b2d1cd352197137698c2aca92bf0ca43bcc640c
Disable downloading `nidaqmx-python` from GitHub.
Manually tested example.

[releases/1.1] examples: Use nidaqmx-python prerelease on PyPI

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
examples/sample_streaming_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml
ni_measurementlink_generator/pyproject.toml
pyproject.toml

Update dependency versions and remove `allow-prereleases`.
Update version number to 1.1.0 so it will be correct in the source zip file.
Ensure that the examples in the released zip file do not automatically download pre-release versions of `ni-measurementlink-service`, `nidaqmx`, etc. from PyPI.
This won't pass the examples check because the dependencies aren't actually released yet.

[releases/1.1] examples: Depend on released dependencies

---

ni_measurementlink_service/__init__.py
ni_measurementlink_service/_internal/discovery_client.py
ni_measurementlink_service/measurement/service.py
ni_measurementlink_service/session_management.py

Add missing type hints, identified with `pyright --verifytypes ni_measurementlink_service`.
Update `__init__.py` to use `__all__` to explicitly re-export imported names. This tells tools like flake8, mypy, and pyright that these imports are re-exported and should be considered part of the public API.
Increase coverage and accuracy of type hints.
Ran `pyright` on `ni_measurementlink_service` as well as the `nidcpower_source_dc_voltage` example. It still produces a lot of errors for partially unknown types and some other conditions, so I'm not ready to add it the GitHub check workflows.

service: Add missing type hints and use __all__ to explicitly re-export names

---

ni_measurementlink_service/measurement/service.py
tests/unit/test_service.py

- Removes the double quotes (") from the annotations whenever they are a string. 
The problem happened because - our Annotations are not all strings we allowed arrays for  Tags and wanted to allow customers to add dictionaries too.  I am using "json.dumps" to help manage that, but the problem is that it also adds quotes to the strings. I tried multiple fixes but this was the simplest I can come up. 
We do not want to display the description or the Title with double quotes. 
Fix and reran tests. 
Manually look at the example:

Fix double quotes on Annotations

---

ni_measurementlink_service/_internal/discovery_client.py
tests/unit/test_discovery_client.py

- This PR redirects the logs to /dev/null (hide logs) when a python measurement starts discovery service.
- Before:
- After:
- Handle `FileNotFoundError` when wrong discovery service .exe path is specified for subprocess.popen function.
- Add tests to register service function to handle `FileNotFoundError` exception.
- Implements [Task 2462367](https://dev.azure.com/ni/DevCentral/_workitems/edit/2462367): When a python measurement starts discovery service, it should not show logs from discovery service to the user.
- Verified discovery service logs are not displayed.
- While the discovery service logs are hidden, it might hide other errors that might arise while starting discovery service through python measurement. To test this case:
-  Specified wrong discovery service .exe path to …

discovery_client: When a python measurement starts discovery service, hide discovery service logs

---

ni_measurementlink_service/_internal/discovery_client.py

- Save the reference of the `subprocess.popen` object to a global variable.
- This prevents leakage of `subprocess` which in turn denotes that the subprocess is still running and produces a `ResourceWarning`.
- Fixes -- Auto-launching the discovery service leaks a `subprocess.Popen`, which produces a `ResourceWarning`. 
- Issue #331 
1. Ran example (nidaqmx_analog_input) service and make sure it is registered with the discovery service.
2. Used Task Manager to kill the discovery service.
3. Manually launched the example service with `poetry run python measurement.py -v`.
4. Verified `ResourceWarning` doesn't happen anymore.
5. Repeated step 1 to 4 for other examples as well.
6. For other examples, in step 3 used `poetry run python -X dev measurement.py` to reproduce the `ResourceWarning`.

discovery_client: Fix auto-launching discovery service producing a ResourceWarning

---

ni_measurementlink_service/_internal/discovery_client.py
tests/unit/test_discovery_client.py

When a measurement and Discovery Service are started in `Debug mode`, the Discovery service from task manager is killed/terminated as soon as the measurement is stopped. So to stop Discovery Service from terminating the following changes are made.
1) Added  a `creationflags` parameter to `subprocess.Popen` in `discovery_client.py`.
2) Set the `creationflags` to `subprocess.CREATE_BREAKAWAY_FROM_JOB`.
3) Updated tests in `test_discovery_client.py` with `creationflags` parameter.
This PR fixes [Bug 2474096](https://dev.azure.com/ni/DevCentral/_workitems/edit/2474096): Discovery Service is terminated when measurement service is stopped in debug mode
Tested these scenarios
Ran `poetry run pytest`. All tests passed.
Ran the tests in debug mode and observed Discovery Service is not terminated …

Added Creation flag CREATE_BREAKAWAY_FROM_JOB to stop Discovery service terminating in Debug mode

---

ni_measurementlink_service/_datatypeinfo.py
ni_measurementlink_service/_internal/parameter/metadata.py
ni_measurementlink_service/measurement/info.py
ni_measurementlink_service/measurement/service.py
tests/unit/test_service.py

For supporting DoubleXYData, we need to support having a 'message_type' field in ParameterMetadata and DataTypeInfo. This PR adds those fields and adds a 'DoubleXYData' DataType. There is no serialization and deserialization supported for this data type yet. So errors will occur if it is used in the `configuration` or `output` decorators at this point. That is to be added shortly.
Preparation step for adding full DoubleXYData support.
Ran all tests locally. Added a configuration and output test to ensure the message_type for DoubleXYData is set on the ParameterMetadata.

Add message_type to ParameterMetadata and DataTypeInfo

---

ni_measurementlink_service/_internal/discovery_client.py
ni_measurementlink_service/_internal/service_manager.py
ni_measurementlink_service/_loggers.py
ni_measurementlink_service/measurement/service.py

Add interceptor classes for logging gRPC client and server calls.
- `nims._loggers.ClientLogger`:
- Debug logging: logs the start and completion of each call.
- `nims._loggers.ServerLogger`:
- Production logging: logs the completion of each call with elapsed time and status code, similar to the logging Serilog provides with ASP.NET Core.
- Debug logging: logs the starts and completion of each call.
As a developer, I want better visibility into MeasurementLink measurement execution time for Python measurement services.
Ran pytest and mypy locally.
Manually tested with nidcpower and streaming examples.

service: Add gRPC client/server call logging interceptors

---

ni_measurementlink_service/_loggers.py
ni_measurementlink_service/_tracelogging.py
poetry.lock
pyproject.toml

Add support for ETW logging using Microsoft's `traceloggingdynamic` package.
Notes:
- PerfView is able to correctly calculate elapsed time for these log messages. 
- I wasn't able to get NI's internal ETW viewer to identify these as paired events. I tried specifying event ids, but sometimes the viewer mismatched client/server calls together.
- This code currently doesn't push/pop the current thread's activity id, so the related activity id is always 0. 
As a developer, I want better visibility into MeasurementLink measurement execution time
Manually tested with PerfView and NI's internal ETW viewer.

service: Add support for ETW logging

---

examples/nidaqmx_analog_input/_helpers.py
examples/nidcpower_source_dc_voltage/_helpers.py
examples/nidigital_spi/_helpers.py
examples/nidmm_measurement/_helpers.py
examples/nifgen_standard_function/_helpers.py
examples/niscope_acquire_waveform/_helpers.py
examples/niswitch_control_relays/_helpers.py
examples/nivisa_dmm_measurement/_helpers.py
examples/output_voltage_measurement/_helpers.py
examples/sample_measurement/_helpers.py
examples/sample_streaming_measurement/_helpers.py
examples/ui_progress_updates/_helpers.py
ni_measurementlink_generator/ni_measurementlink_generator/templates/_helpers.py.mako
ni_measurementlink_generator/tests/test_assets/example_renders/measurement/_helpers.py
ni_measurementlink_generator/tests/test_assets/example_renders/measurement_with_annotations/_helpers.py

T = TypeVar("T") was unused in _helpers.py. This PR deletes it from all _helpers.py files and the templates as well.
Clean up unused code from our examples and generator.
Relying on the PR checks.

Remove unused TypeVar from _helpers.py

---

examples/nidmm_measurement/measurement.py
examples/nifgen_standard_function/measurement.py

Update the translation from the zero enum (e.g. `Waveform.NONE`) to be more readable and concise.
Make the examples more readable.
Manually tested both examples with default, NONE, and a non-default value, using NI IO Trace to verify the value passed to the driver.

examples: Make enum zero translation more readable

---

ni_measurementlink_service/_loggers.py

Update logging exception handlers to pass the exception to `_CallLogger.close()` so it can be logged.
Partial fix for #370 
The part that isn't fixed: when the client calls `measurement_service.context.abort(...)`, this always logs `UNKNOWN` regardless of the gRPC status code that the client specified. This happens because `ServerContext.abort()` raises an empty `Exception` rather than a `RpcError` containing the gRPC status code and details: https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_server.py#L392
Manually tested with `nifgen_standard_waveform`

service: Log exceptions in more cases

---

examples/nidaqmx_analog_input/measurement.py
examples/nidcpower_source_dc_voltage/measurement.py
examples/nidmm_measurement/measurement.py
examples/nifgen_standard_function/measurement.py
examples/niscope_acquire_waveform/measurement.py
examples/niswitch_control_relays/measurement.py
examples/nivisa_dmm_measurement/measurement.py
examples/output_voltage_measurement/measurement.py
examples/sample_measurement/measurement.py
tests/utilities/loopback_measurement/__init__.py

examples:
- Add missing type hints
- Use an event for cancellation, rather than a callback that modifies nonlocal variables
- Name the `MeasurementService` instance consistently
Demonstrate best practices.
Ran mypy on all affected examples. 
Manually tested all affected examples (I think).
Ran pytest.

examples: Add type hints, use cancellation event, name `MeasurementService` consistently

---

ni_measurementlink_service/session_management.py
pyproject.toml
tests/acceptance/test_logging.py
tests/conftest.py

service:
- Rename `Client` to `SessionManagementClient` so it is less confusing to import
tests:
- Add logging acceptance tests
- Add test fixtures for creating `DiscoveryClient`, `GrpcChannelPool`, and `SessionManagementClient`
Logging has no test coverage.
Ran pytest.

tests: Add logging acceptance tests

---

ni_measurementlink_service/measurement/info.py

ni_measurementlink_service/measurement/info.py:
- Revise docstrings. When possible, I reused content from `discovery_service.proto` and `measurement_service.proto`.
- Split up per-attribute docstrings.
- Remove types from docstrings. Sphinx can read PEP 484 type hints.
- Fix Sphinx warnings (for this file only).
Improve documentation readability.
Ran Sphinx and looked at the output.

service: Revise docstrings for info.py

---

ni_measurementlink_service/_channelpool.py
ni_measurementlink_service/measurement/service.py
ni_measurementlink_service/session_management.py

Split `GrpcChannelPool` out of `service.py` and into `_channelpool.py`.
Re-export `GrpcChannelPool` from `service.py`. 
> **Note**
>
> This uses the convention `from foo import bar as bar` to re-export, as documented in https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport
Update context managers to use `typing_extensions.Self`.
Prerequisite for updating client classes to accept a GrpcChannelPool. (Otherwise, it's a circular import.)
Ran pytest.

service: Split GrpcChannelPool into a separate submodule

---

README.md
examples/README.md

Update links to examples to reference MeasurementLink 2023 Q4 and link to the 1.2.0 zip file (which doesn't exist yet)
Prepare for 1.2.0 release.
N/A

README.md: Update links to examples

---

ni_measurementlink_service/_internal/discovery_client.py
tests/unit/test_discovery_client.py

When a measurement service is started without an existing discovery service, it starts the discovery service as a child process. If the measurement service's process(i.e. parent process of the discovery service) is killed, aborted, or by directly closing the application(without proper closure), it also results in the termination of the discovery service.
- When the measurement service console(parent process) is started on `debug mode`, it creates a separate job, which in turn spawns a child process (discovery service). The use of `CREATE_BREAKAWAY_FROM_JOB` ensures the child process is detached from the job([documentation](https://learn.microsoft.com/en-us/windows/win32/procthread/process-creation-flags#flags:~:text=CREATE_BREAKAWAY_FROM_JOB)), preventing the termination of the discovery …

Fix the discovery service to not terminate on parent process closure

---

.github/workflows/check_nims.yml
_docs_source/conf.py
ni_measurementlink_service/_datatypeinfo.py
ni_measurementlink_service/_internal/grpc_servicer.py
ni_measurementlink_service/_internal/parameter/metadata.py
ni_measurementlink_service/_internal/parameter/serializer.py
ni_measurementlink_service/_internal/service_manager.py
ni_measurementlink_service/measurement/service.py
ni_measurementlink_service/session_management.py
poetry.lock
pyproject.toml

Update `check_nims` workflow to generate API reference documentation and check for errors.
Upgrade to latest documentation tools.
Fix or suppress all Sphinx errors and warnings.
Help developers avoid using invalid markup in docstrings.
None.

workflows: Check documentation in `check_nims` and fix Sphinx errors/warnings

---

examples/README.md

Adds game_of_life to list of examples in readme.
Missed this when I checked in the example.
None

Include game_of_life in list of examples

---

examples/README.md

Cherry-pick change adding game of life to list of examples in the readme: #388 
Updated examples list.
None

[releases/1.2] Include game_of_life in list of examples (#388)

---

ni_measurementlink_service/_internal/grpc_servicer.py

`grpc_servicer.py`:
- Remove unnecessary content from docstrings. This class is internal, so we don't need to document each attribute and parameter.
- Delete low-value, "play-by-play" comments
- Delete random capitalization
- Use kwargs to initialize protobuf fields when convenient to do so
- Single-source `_frame_metadata_dict()`
- Prefix member variables with underscore to indicate that they are private
- Remove unnecessary type hints for member variables (the type checker can infer these)
Make `grpc_servicer.py` easier to read and edit.
Ran `poetry run pytest -v`

service: Clean up grpc_servicer.py

---

ni_measurementlink_service/_internal/service_manager.py
ni_measurementlink_service/measurement/service.py

`service_manager.py`:
- Deprecate public attributes that shouldn't be public
- Deprecate `port` attribute and replace it with `service_location`
- Remove unnecessary details from docstrings. This class is internal.
`service.py`:
- Update `MeasurementService` to use `service_location` instead of `port`
- Shorten an error message that users are unlikely to encounter
- Use own `DiscoveryClient` instead of borrowing `GrpcService`'s `DiscoveryClient`
Hide internal implementation details. The entire `GrpcService` class is an internal implementation detail, but we didn't make that clear before, so it's better to have a deprecation period before we break compatibility.
Don't assume the server has only one port.
Ran `poetry run pytest -v`

service: Clean up service_manager.py

---

examples/output_voltage_measurement/measurement.py

When running the OutputVoltageMeasurement I got the following error:
> Traceback (most recent call last):
File "C:\Users\DelpireTest1\Desktop\measurementlink-python\measurementlink-python\examples\output_voltage_measurement\measurement.py", line 177, in <module>
channels: nidcpower._SessionBase,
AttributeError: module 'nidcpower' has no attribute '_SessionBase'
~I am not sure what has happened with `nidcpower._SessionBase`. A search in the ni/nimi-python repo shows this class for our other drivers, DMM, Scope, Switch, etc., but I do not see it for nidcpower.~
Importing nidcpower.session and fixing type hint.
Currently it seems the measurement cannot be run out of the box. This should fix it.
Was able to run the measurement successfully and it worked with both InstrumentStudio and …

Importing nidcpower.session into output voltage measurement

---

ni_measurementlink_service/session_management.py

Update `SessionManagementClient.reserve_session` to roll back the reservation when raising a "Too many sessions reserved" error.
I don't think it's necessary to roll back the "No sessions reserved" case because the session management server's unreserve method would loop over an empty list.
Fixes #400 
Ran new acceptance test (part of separate PR)

service: Update reserve_session to roll back on error

---

examples/output_voltage_measurement/measurement.py

Cherry-pick fix for output voltage measurement.
Original PR: (#399)
Output voltage measurement will not run successfully in 1.2 release if we do not submit this fix.
None

[releases/1.2] Importing nidcpower.session into output voltage measurement (#399)

---

ni_measurementlink_service/_internal/discovery_client.py
tests/unit/test_discovery_client.py

Cherry-pick change on fixing the pywintypes error during the launch of the discovery service after a fresh install of MeasurementLink: #397
Fixes [Bug 2514643](https://dev.azure.com/ni/DevCentral/_workitems/edit/2514643): Auto-launching discovery service fails after clean install (GitHub Issue https://github.com/ni/measurementlink-python/issues/369)
None

[releases/1.2] Fix pywintypes error during the launch of the discovery service after a fresh install of MeasurementLink

---

ni_measurementlink_service/session_management.py

Cherry-pick https://github.com/ni/measurementlink-python/pull/401:
> Update SessionManagementClient.reserve_session to roll back the reservation when raising a "Too many sessions reserved" error.
(cherry picked from commit 761140f06ce60cc5d1edfc83e85aea6a0e1724df)
Fixes #400 
Ran new acceptance test (part of separate PR) in main branch

[releases/1.2] service: Update reserve_session to roll back on error (#401)

---

examples/game_of_life/start.bat
examples/nivisa_dmm_measurement/start.bat
examples/output_voltage_measurement/start.bat

Cherry-pick #416 into releases/1.2.
> game_of_life and output_voltage_measurement:
> - Update start.bat to use a virtualenv.
>
> nivisa_dmm_measurement:
> - Remove outdated comments from start.bat
Make new examples work when statically registered.
Used `install_examples.py` and ran all affected examples.

[releases/1.2] examples: Update start.bat to use virtualenv (#416)

---

scripts/install_examples.py

Update `install_examples.py` to skip dev-dependencies by specifying `--only main`.
Deployed measurement services don't need mypy, etc.
Based on stdout timestamps, the install time for `game_of_life` went from about 20 seconds to about 15 seconds.
Did a full run of `install_examples.py` and tested all examples in InstrumentStudio and (where applicable) TestStand, with fixes from another PR.

scripts: Don't install dev-dependencies into C:\ProgramData

---

examples/game_of_life/pyproject.toml
examples/sample_measurement/pyproject.toml
ni_measurementlink_generator/pyproject.toml
pyproject.toml

Update `ni-measurementlink-service` and `ni-measurementlink-generator` versions to 1.2.0 to work around https://github.com/ni/measurementlink-python/issues/162
Update examples that depend on 1.2 to use the released version.
Use correct version numbers for 1.2.0 build.
None

[releases/1.2] Prepare to release 1.2.0

---

tests/unit/test_discovery_client.py

Fix mypy errors:
```
tests\unit\test_discovery_client.py:267: error: Argument 2 to "error" has incompatible type "None"; expected "str"  [arg-type]
tests\unit\test_discovery_client.py:267: error: Argument 3 to "error" has incompatible type "None"; expected "str"  [arg-type]
```
Main branch should not have mypy errors.
Ran `poetry run mypy tests`

tests: Fix mypy errors

---

.env.sample
.env.simulation
ni_measurementlink_service/_configuration.py
ni_measurementlink_service/_featuretoggles.py
tests/unit/test_configuration.py

Add a `_configuration` submodule, which reads configuration options from the environment or a `.env` file. In later PRs, this will be used to replace the examples' command-line parameters and `ServiceOptions` class.
Update `_featuretoggles` to share the python-decouple `AutoConfig` with `_configuration`.
The new create_session(s) API will use this.
Ran mypy and new unit tests.

service: Add _configuration submodule

---

.github/workflows/Publish_NIMS.yml

When I published 1.1.0, ncipollo/release-action@v1 failed with this error:
```
Error: Error undefined: Tried to update "MeasurementLink Support for Python v1.1.0" which is neither a draft or prerelease. (updateOnlyUnreleased is on)
```
The `Publish_NIMS.yml` workflow doesn't start until you click the *Publish* button, at which
point the release is no longer a draft.
Signed-off-by: Brad Keryan <brad.keryan@ni.com>
(cherry picked from commit 2a5fb2eaf64587c2b0a6a343a736281e012189df)
(cherry picked from PR https://github.com/ni/measurementlink-python/pull/330)
Fix 1.1 release workflow in case we need to patch again.
None

[releases/1.1] Publish_NIMS workflow: Allow updating published releases (#330)

---

.github/workflows/Publish_NIMS.yml
.github/workflows/check_nims.yml
_docs_source/conf.py

Enable more Sphinx extensions:
- githubpages: Automatically create `.nojekyll` file
- intersphinx: Allow linking to docs for the Python stdlib and other packages
Remove `touch docs/.nojekyll` from GitHub workflows.
Show type hints in attribute/parameter descriptions.
Enhance documentation by linking to other docs and showing type hints.
Simplify GitHub workflows.
Built docs locally. Verified that the `.nojekyll` file is created and that hyperlinks to stdlib and nidcpower work.

docs: Enable githubpages, intersphinx, and type hints

---

examples/game_of_life/pyproject.toml
examples/sample_measurement/pyproject.toml

Update examples that depend on 1.2 to use the released version.
> **Note** This will not pass the check-examples PR workflow until 1.2 is released.
Use correct versions
None

examples: Depend on released version

---

.github/workflows/run_tests.yml
ni_measurementlink_generator/poetry.lock
poetry.lock
pyproject.toml

Update `pyproject.toml` to specify a newer version of `grpcio-tools` when using Python 3.12. Continue using the older `grpcio-tools` with older Python versions to avoid any changes to codegen.
Enable Python 3.12 in PR run-tests workflow.
Test with the latest released Python.
Ran `poetry run pytest -v` on a machine with MeasurementLink and Python 3.12 installed. Warnings: https://github.com/ni/measurementlink-python/issues/428
Manually tested `nidcpower_source_dc_voltage` in InstrumentStudio with Python 3.12.
Was unable to load TestStand code modules with Python 3.12 in TestStand 2021 SP1.

Add support for Python 3.12

---

.github/workflows/Publish_NIMS.yml
.github/workflows/check_nims.yml
.github/workflows/run_tests.yml
ni_measurementlink_service/_drivers/_nidcpower.py
ni_measurementlink_service/_drivers/_nidigital.py
ni_measurementlink_service/_drivers/_nidmm.py
ni_measurementlink_service/_drivers/_nifgen.py
ni_measurementlink_service/_drivers/_niscope.py
ni_measurementlink_service/_drivers/_niswitch.py
ni_measurementlink_service/_sessiontypes.py
ni_measurementlink_service/session_management.py
poetry.lock
pyproject.toml
tests/unit/_drivers/_driver_utils.py
tests/unit/_drivers/test_nidcpower.py
tests/unit/_drivers/test_nidigital.py
tests/unit/_drivers/test_nidmm.py
tests/unit/_drivers/test_nifgen.py
tests/unit/_drivers/test_niscope.py
tests/unit/_drivers/test_niswitch.py
tests/unit/_reservation_utils.py
tests/unit/conftest.py
tests/unit/test_reservation.py

Add driver-specific create_session(s) APIs:
- `create_nidcpower_session(s)`
- `create_ndigital_session(s)`
- `create_nidmm_session(s)`
- `create_nifgen_session(s)`
- `create_niscope_session(s)`
- `create_niswitch_session(s)`
Add driver-specific "extras" for each driver, plus a combined "drivers" extra.
Update GitHub workflows:
- `check_nims.yml`: installs all extras.
- `run_tests.yml`: tests with no extras and all extras.
- `Publish_NIMS.yml`: reuses `check_nims.yml`, installs all extras for doc build.
Part of the new session management API.
Ran new unit tests locally.
Manually tested with an updated `nidcpower_source_dc_voltage` (not part of this PR).

service: Add driver-specific create_session(s) APIs for MI drivers

---

ni_measurementlink_service/_drivers/_nidaqmx.py
ni_measurementlink_service/session_management.py
tests/unit/_drivers/test_nidaqmx.py

Add `reservation.create_nidaqmx_task(s)`.
Part of new session management API.
Ran new unit tests. 
Updated DAQmx example to use new API (not part of this PR).

service: Add create_nidaqmx_task(s) API

---

ni_measurementlink_service/session_management/_reservation.py
ni_measurementlink_service/session_management/_types.py
tests/unit/_drivers/test_nidaqmx.py
tests/unit/_drivers/test_nidcpower.py
tests/unit/_drivers/test_nidigital.py
tests/unit/_drivers/test_nidmm.py
tests/unit/_drivers/test_nifgen.py
tests/unit/_drivers/test_niscope.py
tests/unit/_drivers/test_niswitch.py

`_with_typed_session()` was incorrectly assuming that the runtime type matches the static type. Also, it was trying to infer the static type variable `TSession` based on the runtime type expression `type(session)`.
Fixing this revealed a problem with the tests: patching `driver.Session` and replacing it with a mock causes `isinstance` checks to fail. The 2nd argument to `isinstance` must be a type, so it raises an error if `driver.Session` is a `Mock` instance rather than a type. Patching `driver.Session.__new__` instead of `driver.Session` avoids this problem because it ensures that `driver.Session` is still a type. (Patching `driver.Session` to replace it with a subclass that overrides `__new__` would also work.)
These type checks are needed for `get_connection(s)`
Ran updated unit …

service: Fix session type checks

---

ni_measurementlink_service/_drivers/_niswitch.py
ni_measurementlink_service/session_management/_reservation.py
tests/unit/_drivers/test_niswitch.py

Avoid `NISWITCH_ERROR_INVALID_RESOURCE_DESCRIPTOR` when setting `simulate=True` for `create_niswitch_session(s)`.
Fixes a bug found while updating examples.
Ran updated unit tests.
Manually tested with updated examples.

service: Fix NI-SWITCH simulation errors

---

.github/renovate.json
.github/workflows/renovate.yml

Add a GitHub workflow that runs RenovateBot, which is an application that updates dependency lock files for NPM, Poetry, and other development tools.
The docs recommend running it hourly when using the GitHub action: https://docs.renovatebot.com/getting-started/running/#hosting-renovate
There are other ways to host RenovateBot (AzDO pipelines, mend.io hosted application, etc.), and we may switch later if it makes sense.
Fixes https://github.com/ni/measurementlink-python/issues/337
Dependabot keeps complaining about one of our dependencies, but using Dependabot to update `poetry.lock` would upgrade the lock file format, which we don't want to do yet.
Manually tested an earlier version of this config by adding `on: pull_request:`. (This seems to be the easiest way to run a new GitHub …

Add GitHub workflow to run RenovateBot

---

examples/nidmm_measurement/NIDmmMeasurement.seq
examples/nidmm_measurement/teststand_nidmm.py
examples/nidmm_measurement/teststand_pin_map.py
examples/nifgen_standard_function/NIFgenStandardFunction.seq
examples/nifgen_standard_function/teststand_nifgen.py
examples/nifgen_standard_function/teststand_pin_map.py
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.seq
examples/niscope_acquire_waveform/teststand_niscope.py
examples/niscope_acquire_waveform/teststand_pin_map.py

Split TestStand code modules in the examples by pinmap-specific and driver-specific logic and updated the TestStand sequences accordingly.
The `nidmm_measurement`, `nifgen_standard_function`, and `niscope_acquire_waveform` examples' TestStand code modules are split into driver-specific and pin map-specific code.
Implements https://github.com/ni/measurementlink-python/issues/392 for `nidmm_measurement`, `nifgen_standard_function`, and `niscope_acquire_waveform` examples
- Manually tested by running the sequence examples 
- Ran the existing tests.

[PR2] Split the TestStand modules into specific modules for the niscope, nifgen and nidmm examples

---

.github/workflows/Publish_NIMS.yml

`Publish_NIMS.yml`:
- Append variables to `$GITHUB_OUTPUT` instead of using the deprecated `set-output` command.
- Add a `workflow_dispatch` trigger for testing.
Fix this warning:
> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
None. (The `workflow_dispatch` trigger doesn't work until it's committed to main.)

GitHub workflow: Stop using deprecated set-output command

---

examples/nidaqmx_analog_input/measurement.py
examples/nidigital_spi/measurement.py
ni_measurementlink_service/session_management/_reservation.py
ni_measurementlink_service/session_management/_types.py
tests/unit/test_reservation.py

Update the `reservation.session_info` property to include the created session object(s).
In the `SessionInformation._with_session()` and `Connection._with_session()` methods, return the existing instance if the session didn't change. Named tuples are immutable, so there is no benefit in always creating a new instance.
Remove unnecessary calls to `reservation.session_info` from a couple of examples.
Principle of least surprise: `SessionInformation`'s `session` field should reflect session creation.
Ran all tests.
Manually tested updated examples.

service: Update session info property to return created session(s)

---

.github/renovate.json

- Use `config:recommended` preset. This should enable the "dependency dashboard", which is a special GitHub issue that shows the Renovate status and allows us to control it. In particular, this allows us to bypass the schedule and request that Renovate post PRs immediately, which I cannot seem to do with the mend.io developer dashboard.
- Replace `lockFileMaintenance` setting with the `:maintainLockFilesWeekly` preset. (We can change to `:maintainLockFilesMonthly` or `:maintainLockFilesDisabled` if weekly doesn't work out.)
- Remove `onboarding`, `platform`, and `repositories` because these settings are for self-hosted Renovate.
- Remove `forkProcessing` because the default behavior sounds appropriate.
- Remove `dependencyDashboardApproval`, `minimumReleaseAge`, and `gitAuthor` because I …

renovate: Minimize config

---

examples/nidcpower_source_dc_voltage/measurement.py
examples/nidigital_spi/measurement.py
examples/nidmm_measurement/measurement.py
examples/nifgen_standard_function/measurement.py
examples/niscope_acquire_waveform/measurement.py
examples/niswitch_control_relays/measurement.py
examples/nivisa_dmm_measurement/measurement.py
examples/output_voltage_measurement/measurement.py
ni_measurementlink_service/session_management/_reservation.py
tests/unit/_drivers/test_nidcpower.py
tests/unit/_drivers/test_nidigital.py
tests/unit/_drivers/test_nidmm.py
tests/unit/_drivers/test_nifgen.py
tests/unit/_drivers/test_niscope.py
tests/unit/_drivers/test_niswitch.py
tests/unit/test_reservation.py

Rename `create_session(s)` to `initialize_session(s)` for the MI and generic APIs. Keep `create_nidaqmx_task(s)` as-is.
Rename `_create_visa_dmm_session` helper method to `_construct_visa_dmm_session`.
Fixes [AB#2561827](https://dev.azure.com/ni/DevCentral/_workitems/edit/2561827)
Makes the public API more consistent with the `SessionInitializationBehavior` enum and the MI APIs.
Ran tests.

service: Rename create_session(s) to initialize_session(s)

---

ni_measurementlink_service/_featuretoggles.py

Enable the SESSION_MANAGMEMENT_2024Q1 feature toggle by default.
The feature is mostly complete and enabling it by default simplifies manual testing.
Ran all tests.

service: Enable SESSION_MANAGMEMENT_2024Q1 feature toggle by default

---

examples/nifgen_standard_function/teststand_nifgen.py
examples/niswitch_control_relays/teststand_niswitch.py
ni_measurementlink_service/_drivers/_nifgen.py
ni_measurementlink_service/_drivers/_niswitch.py
ni_measurementlink_service/session_management/_reservation.py

Updates the nifgen and niswitch TestStand code modules to use the new session management API. 
Note: Updating the TestStand code modules to use the new session management API will suffice to make sure the simulation config is read from `.env` file.
Uses the same session creation code as for measurements, with simulation via. `.env` file.
Manually tested with TestStand 2021 SP1.

examples: Update TestStand code modules for NI-Fgen and NI-Switch examples

---

examples/nivisa_dmm_measurement/teststand_nivisa_dmm.py
examples/output_voltage_measurement/teststand_nivisa_dmm.py
ni_measurementlink_service/_configuration.py
ni_measurementlink_service/_dotenvpath.py
tests/unit/test_dotenvpath.py

Update `.env` search to include some fallback options if the current directory and its parents don't contain a `.env` file:
- For PyInstaller, use the EXE path
- For scripts that have a `__main__` module that exists on disk, use the script path
- For TestStand code modules (and possibly other cases), use the path of the topmost caller that isn't part of `ni_measurementlink_service`
Fixes [AB#2565326](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2565326)
Ran tests.
Manually tested with nidcpower_source_dc_voltage TestStand sequence.

service: Include TS code module dir in `.env` search

---

ni_measurementlink_service/discovery/_support.py
tests/conftest.py
tox.ini

Change `discovery/_support.py` to get the MeasurementLink install paths from the Windows registry instead of using environment variables like `ProgramW6432` and `ProgramData`.
Eliminate need to list required environment variables in `passenv` in `tox.ini`.
Ran all tests on Windows with 64-bit Python.

service: Get MeasurementLink install paths from registry instead of environment variables

---

.github/workflows/Publish_NIMS.yml
.github/workflows/check_examples.yml
.github/workflows/check_nimg.yml
.github/workflows/check_nims.yml
.github/workflows/run_system_tests.yml
.github/workflows/run_unit_tests.yml

- Caching improvements
- Cache in-project virtualenvs. All of our caching code was still using `~/.cache/pypoetry/virtualenvs`.
- I originally tried using actions/setup-python's built-in caching, but I ran into two problems:
- It requires installing Poetry before Python (e.g. with pipx), and when I did this, tests used the wrong Python version. (pipx is slightly faster than Gr1N/setup-poetry, though.)
- Its cache key setup is limited to simple use cases and can't handle optional extras or Poetry dependency groups.
- Use restore/save for workflows that run `poetry install` multiple times with different extras and/or dependency groups.
- Cache example `poetry.lock` files. These lock files are not checked into Git, but generating them takes over 5 minutes, so they are worth caching.
- For …

Speed up GitHub workflows

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
examples/sample_streaming_measurement/pyproject.toml
examples/ui_progress_updates/pyproject.toml

Change pyproject.toml for examples to remove the dev dependency on the source code path.
Update the examples to depend on the latest prerelease version.
Ran install_examples script and tested various examples. I'm having trouble with NI-DCPower and NI-Scope, but I believe those are machine-specific problems. I'm setting up a newly minted machine to test those and won't submit this until I verify those.

Make examples depend on newly released 1.3.0.dev0

---

.github/workflows/run_system_tests.yml
tests/unit/_drivers/test_nidcpower.py
tests/unit/_drivers/test_nidigital.py
tests/unit/_drivers/test_nidmm.py
tests/unit/_drivers/test_nifgen.py
tests/unit/_drivers/test_niscope.py
tests/unit/_drivers/test_niswitch.py

- Driver acceptance tests needs `.env` file in **root directory** to simulate driver instruments, so moved `examples/.env.simulation` to `.env` in pipeline such that it runs acceptance tests without any errors.
- The configuration in `.env` overrides the session parameter default values in unit tests that doesn't use simulation mode, which fails the tests. So to resolve this issue, passed in the default values when calling initialize session in unit tests.
To run acceptance tests that uses simulated instrument drivers in pipeline.
Manually ran `poetry run pytest`.

[PR1] Move .env.simulation to .env in run_system_tests workflow

---

.readthedocs.yml

Cherry-pick #505 into releases/1.1.
Enable displaying 1.1 docs in RTD.
The config has been tested with the main branch.

[releases/1.1] rtd: Add .readthedocs.yml

---

.readthedocs.yml

Cherry-pick #505 into releases/1.2.
Enable displaying 1.2 docs in RTD.
The config has been tested with the main branch.

[releases/1.2] rtd: Add .readthedocs.yml

---

examples/game_of_life/_helpers.py
examples/nidaqmx_analog_input/_helpers.py
examples/nidcpower_source_dc_voltage/_helpers.py
examples/nidigital_spi/_helpers.py
examples/nidmm_measurement/_helpers.py
examples/nifgen_standard_function/_helpers.py
examples/niscope_acquire_waveform/_helpers.py
examples/niswitch_control_relays/_helpers.py
examples/nivisa_dmm_measurement/_helpers.py
examples/output_voltage_measurement/_helpers.py
examples/sample_measurement/_helpers.py
examples/sample_streaming_measurement/_helpers.py
examples/ui_progress_updates/_helpers.py
ni_measurementlink_generator/ni_measurementlink_generator/templates/_helpers.py.mako
ni_measurementlink_generator/tests/test_assets/example_renders/measurement/_helpers.py
ni_measurementlink_generator/tests/test_assets/example_renders/measurement_with_annotations/_helpers.py

- Removes unused command line arguments and other methods in the measurement generator template and updates the helpers.py copies under each existing example.
Remove the command line arguments from the `_helpers.py` module, that aren't used. [#AB2552336](https://dev.azure.com/ni/DevCentral/_workitems/edit/2552336)
- Manually tested the `NI-DCPower` example.
- Ran `ni_measurementlink_generator` tests.
- Ran mypy for each of the examples.
- Generated and verified the changes in the measurement service.

Remove unused methods in _helpers.py.mako and update its copies under examples

---

tests/unit/test_discovery_client.py

Fixes the `DeprecationWarning` raised due to `Pathlib.Path` where it wasn't expected to be. Fixes #428
Provides the correct type of outputs to match the original API's expected return type.
Ran mypy and pytest.

fix: DeprecationWarning raised due to Pathlib.Path

---

.github/workflows/sync_github_issues_to_azdo.yml

Exclude "Dependency Dashboard" issue when syncing to Azure Devops.
Keep "Dependency Dashboard" out of bug backlog.
None

github: Don't sync dependency dashboard to AzDO

---

.github/workflows/sync_github_issues_to_azdo.yml

Strings in GitHub expressions must use single quotes, not double quotes.
Fix AzDO sync job
None

github: Fix syntax error in `sync_github_issues_to_azdo.yml`

---

.github/renovate.json

Allow Renovate to auto-merge updates to patch versions (1.2.x) and lock file maintenance. It should create a PR at whatever time and then merge it before 4am the next day unless a human reviewer comments on the PR.
Note: I changed the repo settings to allow Renovate to bypass the pull request requirement.
Make approving trivial updates optional.
None

renovate: Automerge patch updates

---

poetry.lock
pyproject.toml

Update Tox version constraint to >=4.0.
https://www.github.com/pypa/virtualenv/issues/2666 caused Tox to be incorrectly downgraded to 3.x.
`poetry lock --no-update` did not complain.

pyproject.toml: Update Tox minimum version to 4.0

---

examples/.env.sample
ni_measurementlink_service/_configuration.py
ni_measurementlink_service/_drivers/_grpcdevice.py
ni_measurementlink_service/_drivers/_nidaqmx.py
ni_measurementlink_service/_drivers/_nidcpower.py
ni_measurementlink_service/_drivers/_nidigital.py
ni_measurementlink_service/_drivers/_nidmm.py
ni_measurementlink_service/_drivers/_nifgen.py
ni_measurementlink_service/_drivers/_niscope.py
ni_measurementlink_service/_drivers/_niswitch.py
tests/unit/_drivers/test_grpcdevice.py

- Extract `get_grpc_device_server_location` in preparation for VISA gRPC support
- Rename gRPC device server option variables and function for consistency
- Change `GRPC_DEVICE_SERVER_ADDRESS` to expect a URL in preparation for TLS support
- Add debug logging
- Add more tests
Consistency & prepare for VISA gRPC (soon) and TLS (later)
Ran unit tests.

service: Rename GRPC_DEVICE_SERVER_ADDRESS and change it to a URL

---

examples/nivisa_dmm_measurement/_visa_dmm_session_management.py
examples/nivisa_dmm_measurement/_visa_grpc.py
examples/nivisa_dmm_measurement/measurement.py
examples/nivisa_dmm_measurement/teststand_nivisa_dmm.py
examples/output_voltage_measurement/_visa_dmm_session_management.py
examples/output_voltage_measurement/_visa_grpc.py
examples/output_voltage_measurement/measurement.py
examples/output_voltage_measurement/teststand_nivisa_dmm.py

Update `nivisa_dmm_measurement` and `output_voltage_measurement` to use NI gRPC Device Server.
`_visa_dmm_session_management.py`, `_visa_grpc.py`, and `teststand_visa_dmm.py` are duplicated or "vendored" in each example.
I would like to move some of the VISA session management code into `ni-measurementlink-service` (https://github.com/ni/measurementlink-python/pull/522 is intended to move in that direction), but for now I'm adding it as example code.
Allow sharing VISA sessions between multiple measurement services.
- Manually tested `nivisa_dmm_measurement` with a physical HP 34401A, simulation, and various permutations of `USE_GRPC_DEVICE_SERVER` and `GRPC_DEVICE_SERVER_ADDRESS`.
- Manually tested `output_voltage_measurement` with physical NI PXIe-4141 and HP 34401A instruments.
- The …

examples: Add gRPC support to VISA examples

---

examples/game_of_life/_helpers.py
examples/nidaqmx_analog_input/_helpers.py
examples/nidcpower_source_dc_voltage/_helpers.py
examples/nidigital_spi/_helpers.py
examples/nidmm_measurement/_helpers.py
examples/nifgen_standard_function/_helpers.py
examples/niscope_acquire_waveform/_helpers.py
examples/niswitch_control_relays/_helpers.py
examples/nivisa_dmm_measurement/_helpers.py
examples/output_voltage_measurement/_helpers.py
examples/sample_measurement/_helpers.py

This removes the PinMapClient class which is unused in the `_helpers.py`.
With the "Update pin map" step, updating the pin map id to the Pin map service is now abstracted from the user. Hence, the PinMapClient class is not required in the `_helpers.py`.
Ran mypy locally.

examples: remove PinMapClient class from _helpers.py

---

.github/workflows/check_examples.yml
.github/workflows/check_nimg.yml
.github/workflows/check_nims.yml
.github/workflows/run_unit_tests.yml

Update GitHub workflows to use the full Python version (e.g. 3.12.1) in the venv cache key, rather than the requested version (e.g. 3.12). This invalidates cached venvs when GitHub deploys a new Python update. Otherwise, the cached venv may refer to a different version of Python than the version than is installed.
Fix #560 
PR build

github: Use full Python version in cache key

---

ni_measurementlink_service/_dotenvpath.py

Use [os.path.exists(path)](https://docs.python.org/3/library/os.path.html#os.path.exists) instead of `Path.exists()` to swallow OS errors for invalid file paths for older Python versions. [AB#2606153](https://dev.azure.com/ni/DevCentral/_workitems/edit/2606153)
When the `.env` file isn't present in any of the measurement.py parent directories and if TestStand adaptors use any Python version <3.8.10 or <3.9.5, an OSError is thrown for invalid file paths. Using `os.path.exists(path)` resolves this error.
Ran mypy and manually ran the "nidcpower_source_dc_voltage" example's sequence file in TestStand 2021 SP1 with Python versions 3.8.9, 3.8.10, 3.9.4, 3.9.5, 3.9.13 and 3.10.11.

fix: use os.path to avoid os errors for invalid file paths

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
ni_measurementlink_generator/pyproject.toml
pyproject.toml

Change versions in release branch 1.3 to be '1.3.0' for packages to be published shortly and also for examples.
See pre-publishing steps in https://github.com/ni/measurementlink-python/wiki/Release-Process#publishing-an-official-release-eg-1x0
Final preparation before publishing the 1.3.0 release.
None. Build should catch checks. Check examples action has been disabled in the releases/1.3 branch protection rule.

Prepublish steps to make version 1.3.0 in packages and examples

---

.github/workflows/Publish_NIMS.yml

If there are no version changes (i.e. the existing version already matched the tag being published), don't commit them.
Allow publish to complete correctly.
None. Will re-run publish job after submitting to see if it works.

Check if NIMS and NIMG versions are different before committing

---

ni_measurementlink_service/session_management/_client.py
ni_measurementlink_service/session_management/_reservation.py

Added a new base class, `_BaseSessionContainer`, responsible for holding common properties which for now include `_session_manager`, `_discovery_client`, and `_grpc_channel_pool`, that can be utilized by both `BaseReservation` and `BaseMultiplexer`. 
[AB#2577300](https://dev.azure.com/ni/DevCentral/_workitems/edit/2577300)
Added a new `_BaseSessionContainer` class to hold common fields/properties for BaseReservation and `BaseMultiplexer` (once that gets added shortly).
- Manually ran the NIDCPower example in both InstrumentStudio and TestStand.
- Executed automated tests.

Create Base Class to Consolidate Common Properties in BaseReservation and BaseMultiplexer

---

tests/unit/test_service.py

Delete duplicate test parameters and fix spelling.
The upgrade to Pytest 8.0 highlighted these by changing how they are formatted:
https://github.com/ni/measurementlink-python/pull/596
PR build

tests: Fix duplicate test parameters

---

ni_measurementlink_service/_internal/utilities/__init__.py

This submodule is unused and we should not add to it.
Keep people from adding code to it.
PR build

service: Delete _internal/utilities submodule

---

examples/.env.sample
ni_measurementlink_service/_featuretoggles.py
ni_measurementlink_service/measurement/service.py
ni_measurementlink_service/session_management/_reservation.py

#516 [AB#2577651](https://dev.azure.com/ni/DevCentral/_workitems/edit/2577651)
Measurement support for Python [v1.3.0](https://github.com/ni/measurementlink-python/releases/tag/1.3.0) has been released and with that the session management feature toggle is redundant.
Existing tests should pass.

cleanup: remove session management feature toggle

---

.github/CODEOWNERS

Remove myself as a codeowner. There are already enough code owners so I am not adding anyone in my place.

Remove Paul as codeowner

---

ni_measurementlink_service/session_management/_client.py
tests/unit/test_session_management.py

Updates the `get_multiplexer_sessions` and `get_all_registered_multiplexer_sessions` APIs to return the MultiplexerSessionContainer object to expose multiplexer initialization APIs.
To expose the initialize multiplexer APIs in the TestStand fixtures.
Updates existing test cases.

nims: update get multiplexer APIs in session management client to return MultiplexerSessionContainer instance

---

examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml

References the about-to-release "ni-measurementlink-service" package (v1.4.0-dev0) in the nidcpower_source_dc_voltage_with_multiplexer example.
This is expected to be merged to `main` post the pre-release of `v1.4.0-dev0`.
Check examples would fail until the 1.4.0-dev0 pre-release is done.

deps: update nims dependency in the new multiplexer example

---

examples/niswitch_control_relays/pyproject.toml
ni_measurementlink_generator/pyproject.toml
pyproject.toml

- Updates the NIMG and NIMS versions in the main branch.
- Updates the NIMS package version in `niswitch_control_relays` example since its teststand_niswitch.py was updated in #625 to hold the niswitch multiplexer session creation and destruction APIs. Ideally this should have went in #637.
Preparation for the upcoming development in 'main' and have the niswitch_control_relays example's NIMS package version updated.
NA.

deps: update main branch versions and update NIMS version in niswitch_control_relays example

---

examples/README.md
examples/nidcpower_source_dc_voltage_with_multiplexer/README.md

Updates the `README.md` with the new multiplexer example.
To have the `README.md` files in sync with the repo changes.
NA.

docs: update examples' README.md

---

ni_measurementlink_service/session_management/_reservation.py

Removes the feature toggle from the `MultiplexerSessionContainer`'s "__init__" method.
[AB#2673383](https://dev.azure.com/ni/DevCentral/_workitems/edit/2673383)
If the examples that don't use multiplexer update their NIMS dependency to `1.4.0-dev0`, a `FeatureNotSupportedError` is thrown.
- Manually verified,
- the "ni_dcpower_source_dc_voltage" measurement _with_ and _without_ enabling the feature toggle (**no** errors were thrown).
- the "ni_dcpower_source_dc_voltage_with_multiplexer" _with_ and _without_ enabling the feature toggle and the `FeatureNotSupportedError` was thrown when the feature toggle wasn't enabled. 
- Existing tests should still pass.

fix: remove feature toggle from MultiplexerSessionContainer's init method

---

examples/niscope_acquire_waveform/NIScopeAcquireWaveform.pinmap
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.seq
examples/niscope_acquire_waveform/measurement.py

- Update the `NI-Scope` example to reserve the session using a pin group by grouping existing pins.
To demonstrate obtaining connections at both the individual pin and pin group levels when reserving the session using a pin group:
- Obtain connections using individual pins.
- Obtain connections using pin groups.
- Manually ran the measurement and verified it from both `InstrumentStudio` and `TestStand`.

examples: Update NI-Scope to demonstrate PinGroup usage

---

examples/niscope_acquire_waveform/pyproject.toml

References the latest pre-release `ni-measurementlink-service` package (v1.4.0-dev1) in the `niscope_acquire_waveform` example.
As the NI-Scope example demonstrates pin group usage, the `ni-measurementlink-service` version should also support pin groups.
Manually ran the measurement and verified it from both `InstrumentStudio` and `TestStand`.

deps: update nims dependency in the NI-Scope example

---

examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltageMultiSite.pinmap

Updates the `NIDCPowerSourceDCVoltageMultiSite.pinmap` to have 4 sites and a separate channel group for each channel in the `DCPower1` instrument.
This enables users to directly reference this pin map in the provided TestStand sequence without any updates.
Manually verified the pin map by using it for Batch model execution in TestStand 2021 SP1.

example: update nidcpower's multisite pinmap to have separate channel groups

---

ni_measurementlink_service/_featuretoggles.py

Turns the `MULTIPLEXER_SUPPORT_2024Q2` feature toggle to RELEASE status, making it on by default.
Mux feature is ready to go. We are about to create the 1.4.0 release branch.
Automated tests. After we create the release, we'll test the examples which need the feature toggle.

Turn on Mux feature toggle for release

---

examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml

Bump example versions to depend on a released version. Remove allow-prereleases flag.
When the publish happens, the examples should work with a released version.
None. Waiting for publish of the release to test.

[Releases/1.4] Bump example versions that need it to 1.4.0

---

README.md
examples/README.md
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml

Update examples in main that were depending on prerelease dependencies to depend on the newly released 1.4.0 version.
Examples are now using released features, so should depend on released packages.
Depending on the automated tests.

Move examples to released package dependency

---

examples/nidcpower_source_dc_voltage/README.md
examples/nidcpower_source_dc_voltage/measurement.py

Updates the `nidcpower_source_dc_voltage` measurement to support multiple instrument sessions. 
Fixes #673.
- Verified the measurement execution in InstrumentStudio using individual site values and "All Sites".
- Verified the measurement execution in TestStand using sequential and batch process models.

example: update nidcpower measurement to support multiple instrument sessions

---

ni_measurementlink_service/session_management/_client.py
tests/unit/test_session_management.py

Adds timeouts while destroying sessions for the measurements in TestStand
Resolves [User Story 2676827](https://dev.azure.com/ni/DevCentral/_workitems/edit/2676827): Add timeout as 10s when destroying sessions in the TestStand sequences
Manually verified by running and aborting the measurement steps in the NI-FGEN and NI-DAQmx examples

Add timeout of 10s for reserve_all_registered_sessions() 

---

ni_measurementlink_service/grpc/loggers.py

Update the return type for `intercept_service` and remove a couple `# type: ignore`s.
https://github.com/shabbyrobe/grpc-stubs/issues/48 is now fixed.
PR build

loggers: Remove workaround for intercept_service type hint bug

---

examples/nidaqmx_analog_input/measurement.py
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/measurement.py
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/measurement.py
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/measurement.py
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/measurement.py
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/measurement.py
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/measurement.py
examples/niscope_acquire_waveform/pyproject.toml
examples/nivisa_dmm_measurement/measurement.py
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/measurement.py
examples/output_voltage_measurement/pyproject.toml
ni_measurementlink_service/_datatypeinfo.py
ni_measurementlink_service/measurement/info.py
ni_measurementlink_service/measurement/service.py
tests/unit/test_service.py
tests/utilities/measurements/nidaqmx_measurement/__init__.py
tests/utilities/measurements/nidcpower_measurement/__init__.py
tests/utilities/measurements/nidmm_measurement/__init__.py
tests/utilities/measurements/nifgen_measurement/__init__.py
tests/utilities/measurements/niscope_measurement/__init__.py
tests/utilities/measurements/niswitch_multiplexer_measurement/__init__.py
tests/utilities/measurements/pin_aware_measurement/__init__.py

- Adds new DataType.IOResource and DataType.IOResourceArray1D enum values for use annotating Configuration or Output parameters. These data types represent a pin or I/O resource like a channel, better supporting the ability to treat pin maps as optional.
- Maps the new IOResource and IOResourceArray1D data types and the existing Pin and PinArray1D data types to the "ioresource" type specialization.
- Adds a deprecation warning if a Pin or PinArray1D Datatype is used with a Configuration or Output parameter.
[AB#2666681](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/2666681)
This updates the python measurement service libraries to better indicate support for both pins and channels.
Updated existing tests to test the new data types.

Update service to use I/O resource specialization instead of Pin

---

examples/nidcpower_source_dc_voltage_with_multiplexer/measurement.py

Following #690, this adds a device reset on the channel in the nidcpower session similar to the `nidcpower_source_dc_voltage` and `output_voltage_measurement` examples.
#695 
Tested using IO Trace using a simulated NI-DCPower and NI-SWITCH.
_Before:_
_Now:_

example: reset source channel in nidcpower with multiplexer measurement

---

CONTRIBUTING.md
README.md
ThirdPartyNotices.txt
ni_measurement_plugin_generator/README.md
ni_measurement_plugin_sdk/__init__.py
ni_measurement_plugin_sdk/_internal/parameter/serialization_strategy.py

Replace documentation and other usages of `MeasurementLink Support for Python` with `Measurement Plugin Support for Python`.
Also replace some more usages of the `ni-measurementlink-service` package name with `ni-measurement-plugin-sdk`.
Newest name for the repo.
None - docs only.

Replace MeasurementLink Support for Python with Measurement Plugin Support for Python

---

examples/game_of_life/measurement.py

Removes the second incrementation of the `generation` variable.
The `generation` variable is mistakenly incremented twice within the while loop.
Kept a breakpoint and verified that the generation value is incremented only once per iteration.

example: game_of_life: remove the second incrementation of generation variable

---

examples/game_of_life/.serviceignore
examples/nidaqmx_analog_input/.serviceignore
examples/nidcpower_source_dc_voltage/.serviceignore
examples/nidcpower_source_dc_voltage_with_multiplexer/.serviceignore
examples/nidigital_spi/.serviceignore
examples/nidmm_measurement/.serviceignore
examples/nifgen_standard_function/.serviceignore
examples/niscope_acquire_waveform/.serviceignore
examples/niswitch_control_relays/.serviceignore
examples/nivisa_dmm_measurement/.serviceignore
examples/output_voltage_measurement/.serviceignore
examples/sample_measurement/.serviceignore

This PR adds `.serviceignore` files to each of the examples in preparation of the Plug-in Library release.
When publishing a plugin to a Plug-in Library, we should exclude the `.venv` folder and the `__pycache__` folder if they are present.  The presence of the `.serviceignore` file will instruct the Plug-in Library CLI to ignore these folders.
Verified that when publishing one of the examples to a Plug-in Library, we ignore these two folders.
**Note**
This PR should not be completed prior to the upcoming release of Plug-in Library.

Add .serviceignore files to the examples

---

.readthedocs.yml

ReadTheDocs build is failing because it is not finding pyproject.toml at the root directory:
https://readthedocs.org/projects/measurement-plugin-python/builds/24965585/
Fix the docs build
None. Will look at the RTD build after submission.

Fix ReadTheDocs build by including working directory for post-install

---

examples/game_of_life/game_of_life.serviceconfig
examples/game_of_life/install.bat
examples/nidaqmx_analog_input/NIDAQmxAnalogInput.serviceconfig
examples/nidaqmx_analog_input/install.bat
examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.serviceconfig
examples/nidcpower_source_dc_voltage/install.bat
examples/nidcpower_source_dc_voltage_with_multiplexer/NIDCPowerSourceDCVoltageWithMultiplexer.serviceconfig
examples/nidcpower_source_dc_voltage_with_multiplexer/install.bat
examples/nidigital_spi/NIDigitalSPI.serviceconfig
examples/nidigital_spi/install.bat
examples/nidmm_measurement/NIDmmMeasurement.serviceconfig
examples/nidmm_measurement/install.bat
examples/nifgen_standard_function/NIFgenStandardFunction.serviceconfig
examples/nifgen_standard_function/install.bat
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.serviceconfig
examples/niscope_acquire_waveform/install.bat
examples/niswitch_control_relays/NISwitchControlRelays.serviceconfig
examples/niswitch_control_relays/install.bat
examples/nivisa_dmm_measurement/NIVisaDmmMeasurement.serviceconfig
examples/nivisa_dmm_measurement/install.bat
examples/output_voltage_measurement/OutputVoltageMeasurement.serviceconfig
examples/output_voltage_measurement/install.bat
examples/sample_measurement/SampleMeasurement.serviceconfig
examples/sample_measurement/install.bat

Adds install scripts and updates the `.serviceconfig` files for all the examples.
Pulling a plug-in from a Plug-in Library will cause DiscoveryService to "install" the plug-in - if an install script is specified.  In order to get `poetry` to install the python dependencies for these examples, we're adding install scripts for them all.
Verified the examples work as expected.

Add Plug-in Library installs scripts to the examples

---

examples/game_of_life/game_of_life.serviceconfig
examples/game_of_life/install.bat
examples/nidaqmx_analog_input/NIDAQmxAnalogInput.serviceconfig
examples/nidaqmx_analog_input/install.bat
examples/nidcpower_source_dc_voltage/NIDCPowerSourceDCVoltage.serviceconfig
examples/nidcpower_source_dc_voltage/install.bat
examples/nidcpower_source_dc_voltage_with_multiplexer/NIDCPowerSourceDCVoltageWithMultiplexer.serviceconfig
examples/nidcpower_source_dc_voltage_with_multiplexer/install.bat
examples/nidigital_spi/NIDigitalSPI.serviceconfig
examples/nidigital_spi/install.bat
examples/nidmm_measurement/NIDmmMeasurement.serviceconfig
examples/nidmm_measurement/install.bat
examples/nifgen_standard_function/NIFgenStandardFunction.serviceconfig
examples/nifgen_standard_function/install.bat
examples/niscope_acquire_waveform/NIScopeAcquireWaveform.serviceconfig
examples/niscope_acquire_waveform/install.bat
examples/niswitch_control_relays/NISwitchControlRelays.serviceconfig
examples/niswitch_control_relays/install.bat
examples/nivisa_dmm_measurement/NIVisaDmmMeasurement.serviceconfig
examples/nivisa_dmm_measurement/install.bat
examples/output_voltage_measurement/OutputVoltageMeasurement.serviceconfig
examples/output_voltage_measurement/install.bat
examples/sample_measurement/SampleMeasurement.serviceconfig
examples/sample_measurement/install.bat

Cherry pick #789 to releases/2.0

[releases/2.0] Cherry-pick: 'Add Plug-in Library installs scripts to the examples (#789)'

---

.github/workflows/Publish_NIMS.yml
.github/workflows/run_unit_tests.yml

Publish of the last pre-release failed because of a missing 'dist' directory.
Ensure publish and prerelease are complete.
None

[releases/2.0] Fix zipping examples during publish

---

packages/generator/pyproject.toml

Changes the name of the plugin generator command to `ni-measurement-plugin-generator`.
We want to change the way users invoke the generator so they don't get confused. `ni-measurement-plugin-sdk-generator` could indicate you're 'generating a plugin SDK'.
Ran the tool locally.

Change the generator tool name to ni-measurement-plugin-generator

---

packages/generator/pyproject.toml

Cherry-pick the change to the measurement plugin generator tool.

[releases/2.0] Cherry-pick: Change the generator tool name to ni-measurement-plugin-generator

---

packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/measurementlink/discovery/v1/discovery_service_pb2.py
packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/measurementlink/discovery/v1/discovery_service_pb2.pyi
packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/measurementlink/discovery/v1/discovery_service_pb2_grpc.py
packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/measurementlink/discovery/v1/discovery_service_pb2_grpc.pyi
packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/measurementlink/sessionmanagement/v1/session_management_service_pb2.pyi
packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/measurementlink/sessionmanagement/v1/session_management_service_pb2_grpc.py
packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/measurementlink/sessionmanagement/v1/session_management_service_pb2_grpc.pyi

This PR updates the generated stubs for the discovery service and session management proto services.  It also updates the ni-apis submodule to refer to the latest commit.
Updated the stubs via `poetry run python .\scripts\generate_grpc_stubs.py`
In preparation for plugin versioning support, we need the latest discovery service APIs.
Automated testing.

Update the stubs for the ni-apis proto files that are out of date

---

packages/service/tests/acceptance/test_measurement_service.py

Disable some of the large-message tests on 32-bit Windows.
Work around #818 
Ran tests/acceptance/test_measurement_service.py locally with Python 3.8.10 32-bit and 64-bit.

service/tests: Disable large message tests on 32-bit Windows

---

packages/service/poetry.lock
packages/service/pyproject.toml
packages/service/tests/acceptance/test_security.py

Update test_security.py to call Process.net_connections() instead of Process.connections().
Update min version of psutil.
Fix this deprecation warning:
```
tests/acceptance/test_security.py::test___loopback_measurement___listening_on_loopback_interface
D:\dev\measurement-plugin-python\packages\service\tests\acceptance\test_security.py:19: DeprecationWarning: connections() is deprecated and will be removed; use net_connections() instead
for conn in psutil.Process().connections()
```
Ran updated test.

service/tests: Fix psutil deprecation warning

---

packages/generator/ni_measurement_plugin_sdk_generator/template.py
packages/generator/ni_measurement_plugin_sdk_generator/templates/measurement.py.mako
packages/generator/ni_measurement_plugin_sdk_generator/templates/measurement.serviceconfig.mako
packages/generator/tests/test_assets/example_renders/measurement/SampleMeasurement.serviceconfig
packages/generator/tests/test_assets/example_renders/measurement/measurement.py
packages/generator/tests/test_assets/example_renders/measurement_with_annotations/SampleMeasurement.serviceconfig
packages/generator/tests/test_assets/example_renders/measurement_with_annotations/measurement.py
packages/service/ni_measurement_plugin_sdk_service/discovery/_client.py
packages/service/ni_measurement_plugin_sdk_service/measurement/info.py
packages/service/ni_measurement_plugin_sdk_service/measurement/service.py
packages/service/tests/assets/example.AllAnnotations.serviceconfig
packages/service/tests/assets/example.CustomAnnotations.serviceconfig
packages/service/tests/assets/example.OnlyCollection.serviceconfig
packages/service/tests/assets/example.OnlyTags.serviceconfig
packages/service/tests/assets/example.serviceconfig
packages/service/tests/assets/example.v2.serviceconfig
packages/service/tests/unit/test_discovery_client.py
packages/service/tests/unit/test_service.py

Add support for reading a measurement's version from its `.serviceconfig` file, as well as passing that version through discovery service's `RegisterService` API.
To do this:
- Make `version` and `ui_file_paths` parameters to the `MeasurementService` constructor optional
- If version is specified in the constructor, use it unless it is also specified in the `.serviceconfig` file AND the two values are different. If the values are different, raise an error
- Add a `version` property to `ServiceInfo`
- Pass `ServiceInfo.version` through the `RegisterServiceRequest` inside the `DiscoveryClient`.
We're working to add version support to our plugins.  The intention is for the version of a plugin to be stored in its `.serviceconfig` file and passed to discovery service when it registers itself. …

Update measurement service to get version from .serviceconfig

---

packages/service/ni_measurement_plugin_sdk_service/discovery/_client.py
packages/service/tests/unit/test_discovery_client.py

- Implementation of the enumerate service API, which return the active measurement services
- Added automation test
- This implementation supports the Interactive Approach for the [Measurement Plug-In client API](https://dev.azure.com/ni/DevCentral/_git/ASW?path=/Specs/Test%20Automation%20Frameworks/E2719769_Support%20for%20Measurement%20Plug-In%20client%20APIs/E2719769_Support%20for%20Measurement%20Plug-In%20client%20APIs.md&version=GBmain&_a=preview&anchor=interactive-approach)'s in python 
Existing and new automated tests passed.

Add enumerate services API

---

README.md
examples/README.md

Re-add links to example downloads, which were removed in the PR that scrubbed the word "MeasurementLink" from the documentation.
Update docs to say the examples are for the next version of InstrumentStudio, since 2024 Q3 has shipped.
Encourage users to use a released version of the software.
N/A

README.md: Re-add links to example downloads

---

packages/service/ni_measurement_plugin_sdk_service/_internal/parameter/_get_type.py
packages/service/ni_measurement_plugin_sdk_service/_internal/parameter/encoder.py
packages/service/ni_measurement_plugin_sdk_service/_internal/parameter/metadata.py
packages/service/ni_measurement_plugin_sdk_service/measurement/service.py
packages/service/tests/unit/test_decoder.py
packages/service/tests/unit/test_metadata.py
packages/service/tests/unit/test_service.py

Resolve issue[#824](https://github.com/ni/measurement-plugin-python/issues/824) and issue[#825](https://github.com/ni/measurement-plugin-python/issues/825).
Fix bugs from PR[#807](https://github.com/ni/measurement-plugin-python/pull/807).
Ran all the tests and checks locally.

Fix invalid test default values and allow double/float parameters take integers

---

examples/nidcpower_source_dc_voltage/measurement.py

* While expanding the `nidcpower_source_dc_voltage` measurement to support multisite in #676, I overlooked the update to the `in_compliance` value in the `_Measurement` tuple. Since tuples are immutable, invoking `_replace()` on a tuple doesn't modify the original tuple; instead, it returns a new tuple with the updated values.
* In the current implementation, the object returned by the `_replace()` method wasn't captured or assigned to any variable, resulting in the use of the original tuple, which did not have the correct "in_compliance" value. This PR ensures that the tuple returned by the `_replace()` method is properly appended to the final `measurements` list.
* Fixes the bug where the `in_compliance` value was not assigned properly.
* Manually verified by running the measurement.

example: use the tuple with the updated "in_compliance" value returned by _replace()

---

.github/renovate.json

Configure Renovate to update Git submodules.
Specify a weekly schedule for updating `third_party/ni-apis`, so it doesn't update for every upstream commit.
Keep `ni-apis` up to date and notify us (via PR build failure) when the checked-in gRPC stubs need to be updated.
When a contributor needs to update `ni-apis` for a new feature, they shouldn't have to deal with past `ni-apis` changes cluttering the diff and/or causing issues.
None

renovate: Automatically update ni-apis submodule

---

.github/workflows/report_test_results.yml
.github/workflows/run_system_tests.yml
.github/workflows/run_unit_tests.yml

Upgrade `actions/upload-artifact` and `actions/download-artifact` to v4. 
Artifacts are now immutable, so upload a separate artifact per test run and merge them when downloading.
The old version is scheduled for deprecation and uses a deprecated Node.js version.
PR build

github: Upgrade upload-artifact and download-artifact to v4

---

packages/generator/poetry.lock
packages/generator/pyproject.toml

- Add "black" to dependency in Measurement Plug-In Client.
- This implementation contains the addition of `black` as package dependency, as fresh machine installation requires `black`.
- Existing automation tests passed.

[Minor] Add dependency to Measurement Plug-In Client

---

packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako

- Add `repr()` function to the string parameters in the `mako template` to omit arbitrary Python code in the output.
[Bug 2843797](https://dev.azure.com/ni/DevCentral/_workitems/edit/2843797)
- If any malicious service returns metadata with escape sequences, that results in arbitrary Python code injection in the output. This implementation handles the escape sequences with `repr()`.
- Tested manually.

fix: Measurement Plug-In Client Generator Python code injection

---

packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/tests/acceptance/test_non_streaming_measurement_client.py
packages/generator/tests/acceptance/test_streaming_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py

- Added Cancel API support to Measurement Plug-In Client.
- Added Test cases for Cancel API.
- Cancel API helps user to cancel the measure and stream-measure gRPC calls.
- Tested manually.
- Executed existing and new automated tests.

Add Cancel API to Measurement Plug-In Client

---

.github/workflows/Publish_NIMS.yml

Fix a build failure when building NIMS. pyproject.toml has moved under packages/service
https://github.com/ni/measurement-plugin-python/actions/runs/10910761526/job/30281908129
Fix build and publish.
None

Fix build of NIMS by including a working-directory

---

packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/tests/acceptance/test_client_generator.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py
packages/generator/tests/utilities/measurements/void_measurement/VoidMeasurement.serviceconfig
packages/generator/tests/utilities/measurements/void_measurement/__init__.py

- Added a measurement with no output configurations to test utilities.
- Added a test case for measurements with no output configuration in `test_client_generator.py`.
- Added a if condition in `mako`, to remove missing imports during the generation of measurements with no output configuration.
- Remove duplicate imports in `mako`.
- Added a new test case to verify the client generation for the measurements with no output configuration.
- Handle unused imports in `mako`. As, some imports are unused in the client module for the measurements with no output configuration.
- Remove duplicate imports i.e., Path is imported twice, as `pathlib` is already added in `mako`, also, we are adding `pathlib`, during client creation of measurement with path configurations.
- Existing and new automation …

Add test case for measurements with no output configuration in client generation acceptance test

---

packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

- Raise an exception to show users that Double XY datatype is not supported, when creating a client for measurements configured with Double XY datatype as inputs.
- Currently, Measurement Plug-In client generator doesn't support Double XY datatype. So, this implementation will state a exact issue of the client generation failure, instead of error stack trace.
- Done manual testing.
- Existing test cases passed.

[Minor] Raise exception during Client creation with Double XY datatype as input configuration

---

packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py

- Updated the Measurement Plug-In Client template to set a default value for the `PinMapContext.sites`.
- When the measurement client is run for a pin-based measurement using IOResource name, sites value of the pin map context input should be explicitly set to 0.  If there are no sites in the pin map context, some measurement would fail with an exception.
**Context**: https://dev.azure.com/ni/DevCentral/_git/983dfe62-3b16-436f-b2ef-d98a72840b64/pullrequest/698395
- Done manual testing.
- Existing and new automation tests passed.

[High Priority] Update default value for the pin map sites

---

packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py
packages/generator/tests/unit/test_measurement_client.py

Cherry-pick the change in PR https://github.com/ni/measurement-plugin-python/pull/916.

[releases/2.1] Cherry-pick: [High priority] Measurement Client: Raise errors for invalid enums

---

packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/tests/acceptance/test_client_generator.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py

- Add test case for checking the mypy issues in the generated Measurement Plug-In Client.
- Fix the existing type hints and mypy issues in `Mako` template.
- Fix the existing type hints in the `mako` template.
- Add mypy check as a test case to check the type hints in the generated Measurement Plug-In Client.
- Done manual testing.
- Existing and new automation tests passed.

Add test case to check mypy error in generated client and fix existing mypy errors

---

packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/tests/acceptance/test_client_generator.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py

Cherry-pick the change in PR #914

[releases/2.1] Cherry-pick: Add test case to check mypy error in generated client and fix existing mypy errors

---

packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

Fix this warning: 
```
ni_measurement_plugin_sdk_generator\client\_support.py:32
C:\actions-runner\1\_work\measurement-plugin-python\measurement-plugin-python\packages\generator\ni_measurement_plugin_sdk_generator\client\_support.py:32: SyntaxWarning: invalid escape sequence '\|'
_INVALID_CHARS = "`~!@#$%^&*()-+={}[]\|:;',<>.?/ \n"
```
Fixes #909 
`poetry run pytest -v`

generator: Fix SyntaxWarning caused by incorrect escape sequence

---

examples/niscope_acquire_waveform/measurement.py
examples/sample_measurement/measurement.py
packages/service/tests/utilities/measurements/nidaqmx_measurement/__init__.py
packages/service/tests/utilities/measurements/nidcpower_measurement/__init__.py
packages/service/tests/utilities/measurements/nidigital_measurement/__init__.py
packages/service/tests/utilities/measurements/nidmm_measurement/__init__.py
packages/service/tests/utilities/measurements/unknown_interface_measurement/__init__.py
packages/service/tests/utilities/measurements/v1_only_measurement/__init__.py
packages/service/tests/utilities/measurements/v2_only_measurement/__init__.py

`niscope_acquire_waveform`: 
- Explicitly convert `measurement_pins` to a `list` before concatenating it to another `list`. 
- Update the type hint to `Sequence[str]`. `Iterable[str]` is also okay.
service/tests:
- Change configuration parameter type hints from `List[T]` to `Iterable[T]`. `Sequence[T]` is also okay.
- Fix incorrect type hints and weird conversions in `nidcpower_measurement`
- Fix incorrect type hints in `nidigital_measurement`
- Fix some test services that didn't have type hints and were returning a float instead of a tuple
After #767, array parameters are represented as a `protobuf`-specific `Sequence[T]` such as `RepeatedScalarFieldContainer[T]`.
Ran updated examples.

examples: Don't assume array parameters are implemented as lists

---

packages/service/ni_measurement_plugin_sdk_service/measurement/service.py
packages/service/tests/acceptance/test_measurement_service.py
packages/service/tests/assets/example.NoVersion.serviceconfig
packages/service/tests/assets/example.v1.serviceconfig
packages/service/tests/unit/test_service.py
packages/service/tests/utilities/measurements/loopback_measurement/LoopbackMeasurement.serviceconfig
packages/service/tests/utilities/measurements/loopback_measurement/__init__.py
packages/service/tests/utilities/measurements/nidaqmx_measurement/__init__.py
packages/service/tests/utilities/measurements/nidcpower_measurement/__init__.py
packages/service/tests/utilities/measurements/nidigital_measurement/__init__.py
packages/service/tests/utilities/measurements/nidmm_measurement/__init__.py
packages/service/tests/utilities/measurements/nifgen_measurement/__init__.py
packages/service/tests/utilities/measurements/niscope_measurement/__init__.py
packages/service/tests/utilities/measurements/niswitch_measurement/__init__.py
packages/service/tests/utilities/measurements/niswitch_multiplexer_measurement/__init__.py
packages/service/tests/utilities/measurements/pin_aware_measurement/__init__.py
packages/service/tests/utilities/measurements/streaming_data_measurement/__init__.py
packages/service/tests/utilities/measurements/unknown_interface_measurement/__init__.py
packages/service/tests/utilities/measurements/v1_only_measurement/__init__.py
packages/service/tests/utilities/measurements/v2_only_measurement/__init__.py
packages/service/tests/utilities/measurements/yield_vs_return_measurement/__init__.py

Fixes #908 
This gives a warning if the 'version' parameter of `MeasurementService` is used. It also errors if there is a 'version' parameter, but no 'version' in the .serviceconfig file. The rule is if you pass a 'version' parameter, you must have the same 'version' in the .serviceconfig file.
Gives clearer guidance on the latest state of the version parameters.
Existing tests plus added one test to verify a RuntimeError in the case where there is a 'version' parameter passed but no version in the .serviceconfig file.

Update version checking to warn that version is deprecated and error if there is no .serviceconfig version

---

packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py
packages/generator/tests/utilities/measurements/non_streaming_data_measurement/NonStreamingDataMeasurement.serviceconfig
packages/generator/tests/utilities/measurements/non_streaming_data_measurement/__init__.py
packages/generator/tests/utilities/measurements/pin_aware_measurement/PinAwareMeasurement.serviceconfig
packages/generator/tests/utilities/measurements/pin_aware_measurement/__init__.py
packages/generator/tests/utilities/measurements/streaming_data_measurement/StreamingDataMeasurement.serviceconfig
packages/generator/tests/utilities/measurements/streaming_data_measurement/__init__.py
packages/generator/tests/utilities/measurements/void_measurement/VoidMeasurement.serviceconfig
packages/generator/tests/utilities/measurements/void_measurement/__init__.py
packages/sdk/pyproject.toml
packages/service/ni_measurement_plugin_sdk_service/discovery/_client.py
packages/service/pyproject.toml
packages/service/tests/unit/test_discovery_client.py

Cherry-pick #925  into releases/2.1.

[releases/2.1] Cherry-pick: Update Measurement Plug-In Generated Client to Resolve with the Corresponding Measurement Service Version 

---

packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

Cherry-pick https://github.com/ni/measurement-plugin-python/pull/932 into releases/2.1.

[releases/2.1] Cherry-pick: generator: Fix SyntaxWarning caused by incorrect escape sequence

---

packages/service/ni_measurement_plugin_sdk_service/measurement/service.py
packages/service/tests/acceptance/test_measurement_service.py
packages/service/tests/assets/example.NoVersion.serviceconfig
packages/service/tests/assets/example.v1.serviceconfig
packages/service/tests/unit/test_service.py
packages/service/tests/utilities/measurements/loopback_measurement/LoopbackMeasurement.serviceconfig
packages/service/tests/utilities/measurements/loopback_measurement/__init__.py
packages/service/tests/utilities/measurements/nidaqmx_measurement/__init__.py
packages/service/tests/utilities/measurements/nidcpower_measurement/__init__.py
packages/service/tests/utilities/measurements/nidigital_measurement/__init__.py
packages/service/tests/utilities/measurements/nidmm_measurement/__init__.py
packages/service/tests/utilities/measurements/nifgen_measurement/__init__.py
packages/service/tests/utilities/measurements/niscope_measurement/__init__.py
packages/service/tests/utilities/measurements/niswitch_measurement/__init__.py
packages/service/tests/utilities/measurements/niswitch_multiplexer_measurement/__init__.py
packages/service/tests/utilities/measurements/pin_aware_measurement/__init__.py
packages/service/tests/utilities/measurements/streaming_data_measurement/__init__.py
packages/service/tests/utilities/measurements/unknown_interface_measurement/__init__.py
packages/service/tests/utilities/measurements/v1_only_measurement/__init__.py
packages/service/tests/utilities/measurements/v2_only_measurement/__init__.py
packages/service/tests/utilities/measurements/yield_vs_return_measurement/__init__.py

Cherry-pick https://github.com/ni/measurement-plugin-python/pull/911 into releases/2.1.

[releases/2.1] Cherry-pick: Update version checking to warn that version is deprecated and error if there is no .serviceconfig version

---

examples/niscope_acquire_waveform/measurement.py
packages/service/tests/utilities/measurements/nidaqmx_measurement/__init__.py
packages/service/tests/utilities/measurements/nidcpower_measurement/__init__.py
packages/service/tests/utilities/measurements/nidigital_measurement/__init__.py
packages/service/tests/utilities/measurements/nidmm_measurement/__init__.py
packages/service/tests/utilities/measurements/unknown_interface_measurement/__init__.py
packages/service/tests/utilities/measurements/v1_only_measurement/__init__.py
packages/service/tests/utilities/measurements/v2_only_measurement/__init__.py

Cherry-pick https://github.com/ni/measurement-plugin-python/pull/924 into releases/2.1.

[releases/2.1] Cherry-pick: examples: Don't assume array parameters are implemented as lists

---

packages/service/tests/unit/test_service.py

Change unit tests for `MeasurementService`'s deprecated `version` parameter to expect deprecation warnings.
Fix test warnings.
Ran `poetry run pytest -v` with Python 3.9, all green.

service/tests: Fix deprecation warnings when specifying version at runtime

---

packages/service/ni_measurement_plugin_sdk_service/discovery/_client.py
packages/service/ni_measurement_plugin_sdk_service/discovery/_types.py
packages/service/ni_measurement_plugin_sdk_service/measurement/info.py
packages/service/tests/unit/test_discovery_client.py

Cherry-pick https://github.com/ni/measurement-plugin-python/pull/948 into releases/2.1.

[releases/2.1] Cherry-pick: [High Priority] Add resolve service with information API in the discovery client (#948)

---

packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

Cherry-pick https://github.com/ni/measurement-plugin-python/pull/949 into releases/2.1.

[releases/2.1] Cherry-pick: [High Priority] Client generator: provide support backward compatibility for Older libraries (#949)

---

packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py
packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/tests/acceptance/test_non_streaming_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py
packages/service/ni_measurement_plugin_sdk_service/measurement/client_support.py

Cherry-pick https://github.com/ni/measurement-plugin-python/pull/931 into releases/2.1.

[releases/2.1] Cherry-pick: [High Priority] Fix Path type conversion and type hints for client codegen

---

packages/service/ni_measurement_plugin_sdk_service/session_management/_reservation.py

During the addition of the `initialize_niswitch_multiplexer_session(s)` APIs, I overlooked the documentation where the environment constant mistakenly pointed to the `NISWITCH` constant instead of the `NISWITCH_MULTIPLEXER` variant.
Ensures the documentation of the APIs is true and correct.
NA.

docs: update the initialize_niswitch_multiplexer_session(s) APIs docstring

---

.github/workflows/Publish_NIMS.yml

Allows publishing to proceed if the generator depends on a service package that is not published yet.
**NOTE:** I intend to cherry-pick this to main after.
Removes check that won't ever pass the way our release process works.
N/A We'll see on publish.

Remove check_nimg from publish_nims workflow

---

.github/workflows/CI.yml

Removes the need for check_nimg to pass before running the unit tests.
We need the unit tests to run for the pre-publish steps even if check_nimg is failing.

Remove requirement for check_nimg to run the unit tests

---

packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

- Provide unique module names for the generated measurement clients by appending a numerical suffix (_1, _2, etc.) to the name during multiple client generation and interactive mode.
- When creating multiple clients, one Python measurement client for the service class `ni.examples.SampleMeasurement_Python` and one LabVIEW measurement client for `ni.examples.SampleMeasurement_LabVIEW` will both be framed with the module name `sample_measurement_client`, leading to file overwriting.
- In this implementation, we will be appending a numerical suffix to provide unique module name to mitigate the above case.
**Context** - [Bug 2894546](https://dev.azure.com/ni/DevCentral/_workitems/edit/2894546)
- Existing test cases passed.
- Tested manually.

Provide unique module names for the generated measurement clients during multiple client generation

---

.github/workflows/PR.yml

Enable `concurrency.cancel-in-progress` for PR.yml, like @maxxboehme did in https://github.com/ni/grpc-device/pull/1104
Minimize resource usage when pushing multiple changes.
None, PR build

GitHub: Auto-cancel PR builds when new changes are pushed

---

packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

Update the client generator to remove a `_NET` suffix from the service class name when generating the default module/class names.
Fixes #975 
```
(.venv) PS D:\dev\measurement-plugin-python\examples\client> ni-measurement-plugin-client-generator --all
...
The measurement plug-in client for the service class 'ni.examples.SampleMeasurement_NET' has been successfully created as 'sample_measurement_client.py'.
The measurement plug-in client for the service class 'ni.examples.SampleMeasurement_Python' has been successfully created as 'sample_measurement_client2.py'.
...
```

generator: Remove _NET suffix from service class base name

---

packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/plugin/__init__.py

Add `--verbose` option to client generator.
Fix a type hint in plugin generator.
Fixes #976 
Ran client generator with `-vv`, `-v`, and no `-v`'s. Got many debug logs with `-vv`.

generator: Add --verbose option to client generator

---

packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/sdk/poetry.lock
packages/sdk/pyproject.toml
packages/service/pyproject.toml

Change the `ni-measurement-plugin-sdk` package to use file paths to depend on `ni-measurement-plugin-sdk-generator ` and `ni-measurement-plugin-sdk-service` during PR/CI builds. This will prevent storing PyPI links to the generator/service packages in the sdk package's `poetry.lock` file.
Update `ni-measurement-plugin-sdk-generator ` to depend on the 2.1.0 released version of `ni-measurement-plugin-sdk-service`.
Update all of the the version numbers to 2.2.0-dev0.
Attempt to resolve the problems that led to this weird version update: https://github.com/ni/measurement-plugin-python/pull/981
PR build

Update package versions and update sdk to use file paths rather than PyPI

---

packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py

- Updated the client generator to raise a click exception for unsupported datatypes, by validating the message type after getting the metadata.
- Added `try-except` block to catch the exceptions raised during the creation of multiple clients and for all registered measurements. Also, show warning message about client creation failure and continue client creation for subsequent measurements.
- This implementation fixes the following issues,
- #974 
- #906 
- Done manual testing
- Existing automation test passed

Handle unsupported message type errors in client generator

---

packages/service/ni_measurement_plugin_sdk_service/discovery/_support.py
packages/service/tests/unit/test_discovery_client.py

Uses a null STDIN handle when starting the discovery service, so that the discovery service doesn't steal STDIN from the shell.
Fixes #943 
Reproduced the issue by killing the discovery service and running plugin-client-generator, and did the same to verify the fix.

Pass null stdin to discovery service

---

examples/sample_measurement/measurement.py
examples/sample_measurement/pyproject.toml
packages/generator/ni_measurement_plugin_sdk_generator/client/__init__.py
packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py
packages/generator/tests/acceptance/test_non_streaming_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/utilities/measurements/non_streaming_data_measurement/__init__.py
packages/service/ni_measurement_plugin_sdk_service/_datatypeinfo.py
packages/service/ni_measurement_plugin_sdk_service/measurement/info.py
packages/service/tests/unit/test_service.py

Adding Support for Double2DArray Output for Client Generator and Service and updating Sample Measurement Example.
Add Double2DArray Output support for measurements.
- All automated tests for Client Generator and Service are running fine after adding Double2DArray output parameter.
- Measurement is running fine through command-line.
- Additional testing on MeasurementUI Editor by dropping Control and Indicator and connecting to measurement produce desired behavior.

Adding Output Support for Double2DArray for Client Generator and Service and updating Sample Measurement Example

---

packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/sdk/poetry.lock
packages/sdk/pyproject.toml
packages/service/pyproject.toml

Update all of the the version numbers to 2.3.0-dev0.
Update ni-measurement-plugin-sdk-generator  to depend on the 2.2.0 released version of ni-measurement-plugin-sdk-service.
Fixing Error related to version constraints while development.
PR Build

fix: update version to 2.3.0-dev0 for measurement packages

---

packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/protobuf/types/array_pb2.py
packages/service/ni_measurement_plugin_sdk_service/_internal/stubs/ni/protobuf/types/array_pb2.pyi

Array.proto was recently updated in [ni-apis](https://github.com/ni/ni-apis/pull/77). We want update it for adding String2DArray support.
Access to array.proto gRPC message types.
None. PR build should be sufficient.

Update to latest ni-apis and add regenerated stubs for array.proto

---

.github/workflows/run_unit_tests.yml
examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/measurement.py
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
packages/generator/README.md
packages/generator/ni_measurement_plugin_sdk_generator/client/_support.py
packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/generator/tox.ini
packages/sdk/README.md
packages/sdk/poetry.lock
packages/sdk/pyproject.toml
packages/service/README.md
packages/service/ni_measurement_plugin_sdk_service/_dotenvpath.py
packages/service/poetry.lock
packages/service/pyproject.toml
packages/service/tox.ini

Remove support for Python 3.8.
NI's Python support policy says:
> NI products that support or integrate with Python will drop official support for all Python versions that have reached their end of life [EOL](https://devguide.python.org/devcycle/#end-of-life-branches) . This should be done at the next release of the product following the EOL date for a given Python version
Also, more of measurement-plugin-python's dependencies (e.g. `protobuf`) have started to drop Python 3.8 support.
PR build.

Remove support for Python 3.8

---

README.md
examples/game_of_life/pyproject.toml
examples/sample_measurement/pyproject.toml
packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/generator/tox.ini
packages/sdk/poetry.lock
packages/service/poetry.lock
packages/service/pyproject.toml
packages/service/tox.ini

Remove the upper bound on `protobuf` version, allowing customers to use `protobuf` v5, v6, etc. in measurement plug-ins.
Add test coverage for `protobuf` v4 vs. v5 vs. v6. 
We do our gRPC codegen with Python 3.9 and `grpcio-tools` v1.49, which forces Poetry to lock `protobuf` v4. When we add Python 3.13 support, it will use a newer `grpcio-tools` and `protobuf` v5, since the older versions don't support Python 3.13.
Fixes #677 
Ensure compatibility with `protobuf` v5 and v6, which bumped the major version due to breaking changes.
Ran `poetry run tox -e py39-pb6` on my test machine.
Using PR build to run full test matrix.

Loosen protobuf version constraint and add protobuf v4/5/6 to the test matrix

---

.github/workflows/Publish_NIMS.yml
.github/workflows/check_examples.yml
.github/workflows/check_nimg.yml
.github/workflows/check_nims.yml
.github/workflows/run_unit_tests.yml
.readthedocs.yml
packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/generator/tox.ini
packages/service/poetry.lock
packages/service/pyproject.toml
packages/service/tox.ini

Update GitHub workflows to run tests with Python 3.13.
Use Python 3.11.9 by default for non-versioned scripts/testing. This is the newest Python version supported by `grpcio-tools` 1.49. Upgrading these workflows to Python 3.12 will break compatibility with `grpcio` 1.49-1.58 and upgrading to 3.13 will break compatibility with `grpcio` 1.49-1.66.
Follow NI Python versioning policy.
PR build.

Add support for Python 3.13

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/sdk/poetry.lock
packages/sdk/pyproject.toml
packages/service/pyproject.toml

Pre-publish steps for releases/2.3.
Standard release procedure.
N/A - PR

(Pre-Publish Steps): update service package version to 2.3

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/output_voltage_measurement/pyproject.toml
examples/sample_measurement/pyproject.toml
packages/generator/ni_measurement_plugin_sdk_generator/client/templates/measurement_plugin_client.py.mako
packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/localized_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/non_streaming_data_measurement_client.py
packages/generator/tests/test_assets/example_renders/measurement_plugin_client/void_measurement_client.py
packages/service/ni_measurement_plugin_sdk_service/grpc/loggers.py
packages/service/poetry.lock
packages/service/pyproject.toml

Replace `grpc-stubs` with `types-grpcio`.
Retrofit for differences between `grpc-stubs` and `types-grpcio`:
- Typing-only types like `CallFuture` and `CallIterator` now have an underscore prefix.
- The type stubs for abstract base classes like `Call`, `Future`, etc. now use `ABCMeta`, so mypy now knows they're abstract. 
The `grpc-stubs` package is archived and will not be updated.
The abstract base class change was a fix for a bug that I reported.
Ran nps, mypy, pytest locally on a machine w/o InStudio or drivers.

Update to typeshed version of gRPC stubs

---

packages/service/ni_measurement_plugin_sdk_service/_tracelogging.py
packages/service/poetry.lock
packages/service/pyproject.toml

Update the `traceloggingdynamic` package in `poetry.lock`.
Remove `ignore_missing_imports` for `traceloggingdynamic`.
Fix a couple of typing errors in the `_tracelogging` submodule.
I contributed a change to add a `py.typed` marker file to the `traceloggingdynamic` package and it has been published to PyPI: https://github.com/microsoft/tracelogging/pull/74
Ran `poetry run nps lint` and `poetry run mypy`

service: Enable type checking for tracelogging

---

packages/service/_docs_source/conf.py
packages/service/poetry.lock
packages/service/pyproject.toml

Upgrade to the latest Sphinx, which requires Python 3.11 or later.
Change copyright year to "2022-2025" to reflect the first year when this package and its documentation were published.
Use `%Y` placeholder to specify the year. 
> [!NOTE]
> The package name was `ni-measurement-service` in 2022, then it was renamed to `ni-measurementlink-service` in 2023, and renamed again to `ni-measurement-plugin-sdk-service` in 2024.
Reformat `pyproject.toml` because I have my editor configured to reformat now.
While setting up Sphinx for another project, I noticed that the Python 3.9 version constraint requires using a Sphinx version from 2023 and the `%Y` placeholder was not supported with that older version.
Ran `poetry run sphinx-build _docs_source docs -b html -W --keep-going` and inspected the …

docs: Upgrade Sphinx and change copyright year to "2022-%Y"

---

.github/workflows/check_nims.yml
CONTRIBUTING.md

Remove `--keep-going` from the Sphinx command line
`--keep-going` is always enabled in Sphinx 8.1+: https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going
PR build

docs: Remove Sphinx --keep-going option

---

.github/workflows/CI.yml
.github/workflows/PR.yml
.github/workflows/Publish_NIMS.yml
.github/workflows/report_test_results.yml

Currently, this repo's **Workflow permissions** setting is set to **Read and write permissions** (Workflows have read and write permissions in the repository for all scopes.). We should change it to **Read repository contents and packages permissions** (Workflows have read permissions in the repository for the contents and packages scopes only.) to reduce the privileges of jobs that run test code.
Specify permissions on the job level, not the workflow level. Specifying permissions on the workflow level grants the specified permissions to all jobs in the workflow, which gives some jobs permissions that they don't need.
CI.yml has multiple jobs, and only one needs additional privileges. I also updated workflows that have only one job.
Principle of least privilege
Tested the same change in …

github: Specify required permissions for each job

---

.github/renovate.json

Enable [helpers:pinGitHubActionDigestsToSemver](https://docs.renovatebot.com/presets-helpers/#helperspingithubactiondigeststosemver), which causes Renovate to do two things:
- Replace `actions/whatever@v3` with `actions/whatever@<sha-hash> # v3`
- Replace `actions/whatever@<sha-hash> # v3` with `actions/whatever@<sha-hash> # v3.1.7`
Pinning GitHub action digests improves build reproducibility and is a security best practice.
Tested in https://github.com/ni/nitypes-python/blob/main/.github/renovate.json

renovate: Pin GitHub Action digests

---

packages/service/poetry.lock
packages/service/pyproject.toml

Remove dependency on `tomlkit`.
I don't think we're using it. `_docs_source/conf.py` is using `toml` which is a separate package.
PR build.

docs: Remove tomlkit dependency

---

packages/service/ni_measurement_plugin_sdk_service/_tracelogging.py.orig
packages/service/poetry.lock
packages/service/poetry.lock.orig
packages/service/pyproject.toml

Cherry-pick https://github.com/ni/measurement-plugin-python/pull/1123
Original PR description: 
Update the `traceloggingdynamic` package in `poetry.lock`.
Remove `ignore_missing_imports` for `traceloggingdynamic`.
Fix a couple of typing errors in the `_tracelogging` submodule.
I contributed a change to add a `py.typed` marker file to the `traceloggingdynamic` package and it has been published to PyPI: https://github.com/microsoft/tracelogging/pull/74
Ran `poetry run nps lint` and `poetry run mypy`

[releases/2.3] service: Enable type checking for tracelogging

---

.github/renovate.json5

Update Renovate config to use `matchManagers` not `matchCategories` for `github-actions`.
The manager name is `github-actions` and the category is `ci`.
None

github: Fix github-actions package rules

---

packages/generator/poetry.lock
packages/generator/pyproject.toml
packages/generator/tests/conftest.py

generator:
- Specify click versions separately for Python 3.9 vs. Python 3.10+
- Update tests to support click 8.2. The CliRunner constructor's `mix_stderr` parameter has been removed. Instead, there is a separate `output` property containing the mixed stream.
I am not updating the examples. They will continue to use the old click until we drop Python 3.9 support later this year.
click no longer supports Python 3.9. Specifying multiple versions allows Poetry to lock different versions for Python 3.9 vs. Python 3.10+, which allows Renovate to keep this package up to date for testing and development.
PR build

fix(deps): Enable testing with latest click

---

packages/generator/tests/acceptance/test_streaming_measurement_client.py
packages/generator/tests/utilities/measurements/streaming_data_measurement/__init__.py

Add a "measurement started" event object to `packages\generator\tests\utilities\measurements\streaming_data_measurement\__init__.py` and update `packages\generator\tests\acceptance\test_streaming_measurement_client.py` to wait for the event before cancelling.
I previously suggested this in https://github.com/ni/measurement-plugin-python/pull/870#discussion_r1752939058 . It looks like @Jotheeswaran-Nandagopal thought I was talking about a different event and I overlooked the fact that the comment thread had been closed without implementing the suggestion.
Fixes #1172 and [AB#3162086](https://dev.azure.com/ni/94b22d7b-ad7b-4f5e-88f0-867910f91c94/_workitems/edit/3162086)
Ran `poetry run pytest -v --count 100000 -x -k test___non_streaming_measurement_execution___cancel___cancels_measurement …

tests: Fix race condition in client cancellation tests

---

packages/service/ni_measurement_plugin_sdk_service/_dotenvpath.py
packages/service/tests/unit/test_dotenvpath.py

`_dotenvpath`:
- Change `nims_path` to `package_path`
- Use `sys.modules[__package__]` instead of hardcoding package name
Incorporate feedback from https://github.com/ni/nidaqmx-python/pull/799
Ran unit tests

service: Remove hardcoded nims references from _dotenvpath

---

packages/service/tests/acceptance/test_nidcpower_measurement.py
packages/service/tests/acceptance/test_nidigital_measurement.py
packages/service/tests/acceptance/test_nidmm_measurement.py
packages/service/tests/acceptance/test_nifgen_measurement.py
packages/service/tests/acceptance/test_niscope_measurement.py
packages/service/tests/acceptance/test_niswitch_measurement.py
packages/service/tests/acceptance/test_session_management.py
packages/service/tests/integration/session_management/test_nidcpower_reservation.py
packages/service/tests/integration/session_management/test_nidigital_reservation.py
packages/service/tests/integration/session_management/test_nidmm_reservation.py
packages/service/tests/integration/session_management/test_nifgen_reservation.py
packages/service/tests/integration/session_management/test_niscope_reservation.py
packages/service/tests/integration/session_management/test_niswitch_reservation.py

I found that around 30 of the service tests fail when I have InstrumentStudio 2025Q3 installed locally. The problem was that the session management service started appending the driver name in front of the resource name for the session in Q3. For example, the session name became 'niDCPower-DCPower1/0' instead of just 'DCPower1/0'. The test machines are still using an older version of InstrumentStudio, so until we upgrade that, we have to allow for both versions.
Allows either version of the session name and tests can pass locally and on the test machines.
Ran the tests locally with InstrumentStudio 2025Q3. Test machines will validate older InstrumentStudio.

Fix tests with resource names when InstrumentStudio 2025Q3 is installed

---

examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/sample_measurement/pyproject.toml
packages/generator/pyproject.toml
packages/sdk/pyproject.toml
packages/service/pyproject.toml

Bump versions in main for generator, sdk, and service to 3.0.0-dev0
Distinguish from releases/2.4 branch, soon to be released. Bump major version since we've deprecated some code. Standard release process.
```
"After creating a new release branch, update pyproject.toml in the main branch to have the next pre-release version number.
For example, after creating releases/1.2, update pyproject.toml to specify version = "1.3.0-dev0".
This reduces confusion about which branch is which."
```
PR

Bump versions to 3.0.0-dev0

---

examples/game_of_life/pyproject.toml
examples/nidaqmx_analog_input/pyproject.toml
examples/nidcpower_source_dc_voltage/pyproject.toml
examples/nidcpower_source_dc_voltage_with_multiplexer/pyproject.toml
examples/nidigital_spi/pyproject.toml
examples/nidigital_spi/teststand_nidigital.py
examples/nidmm_measurement/pyproject.toml
examples/nifgen_standard_function/pyproject.toml
examples/niscope_acquire_waveform/pyproject.toml
examples/niswitch_control_relays/pyproject.toml
examples/nivisa_dmm_measurement/pyproject.toml
examples/nivisa_dmm_measurement/teststand_nivisa_dmm.py
examples/output_voltage_measurement/pyproject.toml
examples/output_voltage_measurement/teststand_nivisa_dmm.py
examples/sample_measurement/pyproject.toml
packages/service/ni_measurement_plugin_sdk_service/__init__.py
packages/service/ni_measurement_plugin_sdk_service/session_management/_reservation.py
packages/service/ni_measurement_plugin_sdk_service/session_management/_types.py

Cherry pick from #1250
Adds back in the session_management to __all__ in the ni_measurement_plugin_sdk_service. This was removed when we started consuming packages from ni-apis-python (see #1220), but not restored with #1228.
Also updating the examples pyproject.toml to allow version 3.0.
Examples are broken when upgrading to the 3.0.0 version.
Installed ni_dcpower_source_voltage example with a local 3.0.1 and ensured it ran correctly.

[Cherry pick from releases/3.0] Restore session_management module export
